import { i18nStore } from "@/shared/store"

// API error code translation
export const translations = {
    NON_INCREASING_TIMES: [
        "Time jump backwards from {} to {}.",
        "Zeitsprung rückwärts von {} nach {}.",
        "Saut dans le temps en arrière de {} à {}.",
        "Tijdsprong achteruit van {} naar {}.",
        "",
        "Il tempo salta indietro da {} a {}.",
    ],
    NON_VALID_FIXES: [
        "The file contains {} non valid fixes.",
        "Die Datei enthält {} ungültige Aufzeichnungen.",
        "Le fichier contient {} enregistrements invalides.",
        "Het bestand bevat {} ongeldige fixes.",
        "",
        "Il file contiene {} non validi"
    ],
    MULTIPLE_A_RECORDS: [
        "Multiple A Records provided.",
        "Mehrere A Records vorhanden.",
        "Plusieurs A Records disponibles.",
        "Meerdere A-Records verstrekt.",
        "",
        "Più record A forniti.",
    ],
    NO_I_RECORD: [
        "NO I Record provided.",
        "Keine I Records vorhanden.",
        "Pas de I Records disponible(s).",
        "Geen I-Records verstrekt.",
        "",
        "Nessun record I fornito.",
    ],
    MULTIPLE_I_RECORDS: [
        "Multiple I records provided.",
        "Mehrere I Records vorhanden.",
        "Plusieurs I Records disponibles.",
        "Meerdere I-Records verstrekt.",
        "",
        "Più record I forniti.",
    ],
    INVALID_H_RECORD: [
        "Invalid H record: {}.",
        "Ungültiger H Record: {}.",
        "H Record invalide: {}.",
        "Ongeldig H-Record: {}",
        "",
        "Record H non valido: {}",
    ],
    PRESS_ALT_VIOLATIONS: [
        "Pressure altitude range from {} to {} is exceeded in {} fixes.",
        "Gültiger Höhenbereich von {} bis {} wird in {} Aufzeichnungen überschritten.",
        "L'altitude valide de {} à {} a été dépassée dans {} traces GPS.",
        "Het drukhoogtebereik van {} tot {} wordt overschreden in {} fixes.",
        "",
        "L'intervallo dell'altitudine di pressione da {} a {} è stato superato in {} correzioni.",
    ],
    GNSS_ALT_VIOLATIONS: [
        "GNSS altitude range from {} to {} is exceeded in {} GNSS fixes.",
        "Gültiger GPS-Höhenbereich von {} bis {} wird in {} Aufzeichnungen überschritten.",
        "L'altitude GPS valide de {} à {} a été dépassée dans {} traces GPS.",
        "GPS hoogtebereik van {} tot {} wordt overschreden in {} fixes",
        "",
        "L'intervallo di altitudine GNSS da {} a {} è stato superato in {} correzioni GNSS.",
    ],
    C_RECORD_TOO_LONG: [
        "C records contains more than 10 lines, not able to parse task.",
        "C Records enthält mehr als 10 Zeilen, Aufgabe kann nicht ausgelesen werden.",
        "C Records contient plus de 10 lignes, la déclaration de vol ne peut pas être lue.",
        "C-Records bevat meer dan 10 regels, niet mogelijk de opdracht uit te lezen.",
        "",
        "I record C contengono più di 10 righe, non sono in grado di analizzare l'attività.",
    ],
    NO_LANDING: [
        "Did not detect landing.",
        "Landung nicht erkannt.",
        "Atterrissage non détecté.",
        "Landing niet herkend.",
        "",
        "Non è stato rilevato un atterraggio.",
    ],
    FUTURE_FLIGHT: [
        "Flight date is from future.",
        "Datum des Fluges liegt in der Zukunft.",
        "La date du vol se trouve dans le futur.",
        "Vluchtdatum ligt in de toekomst.",
        "",
        "La data del volo è nel futuro.",
    ],
    NO_A_RECORD: [
        "No A Record provided.",
        "Kein A Records vorhanden.",
        "Pas de A Records disponible(s).",
        "Geen A-Record verstrekt.",
        "",
        "Nessun record A fornito.",
    ],
    INVALID_QNH_VALUE: [
        "Determined QNH of {} hPa (based on altitude provided) is not between limits of {} hPa and {} hPa.",
        "Festgestelltes QNH von {} hPa (basierend auf der gegebenen Höhe) liegt außerhalb der Grenzen von {} hPa und {} hPa.",
        "Le QNH détecté de {} hPa (basé sur l'altitude donnée), se trouve en dehors des limites de {} hPa et {} hPa.",
        "Vastgestelde QNH van {} hPa (Gebaseerd op de verstrekte hoogte) ligt niet tussen de limiten van {} hPa en {} hPa.",
        "",
        "Il QNH determinato di {} hPa (in base all'altitudine fornita) non è compreso tra i limiti di {} hPa e {} hPa.",
    ],
    PRESS_ALT_NOT_VALID: [
        "Pressure altitude in file is not valid, maximum value is {} meters.",
        "Druckhöhe in der Datei ist ungültig, maximale Höhe beträgt {} Meter.",
        "L'altitude de densité est invalide, l'altitude maximale est de {} mètres.",
        "Druk hoogte in het bestand is ongeldig, maximale waarde is {} meter.",
        "",
        "L'altitudine della pressione nel file non è valida, il valore massimo è {} metri.",
    ],
    A_RECORD_TOO_SHORT: [
        "A Record is too short.",
        "A Record ist zu kurz.",
        "A Record est trop court.",
        "A-Record is the kort.",
        "",
        "Il record A è troppo corto.",
    ],
    H_RECORD_NO_DATE: [
        "No date in H Record provided.",
        "Kein Datum im H Record vorhanden.",
        "Pas de date disponible dans H Record.",
        "Geen datum in H-Record verstrekt.",
        "",
        "Nessuna data in H record fornito",
    ],
    NO_H_RECORD: [
        "No H Record provided.",
        "Kein H Record vorhanden.",
        "Pas de H Record disponible.",
        "Geen H-Record verstrekt.",
        "",
        "Nessun record H fornito.",
    ],
    MAX_GNSS_ALT_REACHED: [
        "Max GNSS sensor altitude is: {}, you reached: {}",
        "Maximale GNSS-Sensorhöhe des Loggers sind {} Meter, du hast {} Meter erreicht.",
        "L'altitude maximale du capteur GNSS de l'enregistreur est de {} mètres, tu as atteint {} mètres.",
        "Maximale GPS-sensorhoogte van de logger is {}, je hebt {} meter bereikt.",
        "",
        "L'altitudine massima del sensore GNSS è: {}, hai raggiunto: {}",
    ],
    MAX_PRESS_ALT_REACHED: [
        "Maximum pressure sensor altitude is: {}, your reached: {}",
        "Maximale Druck-Sensorhöhe des Loggers sind {} Meter, du hast {} Meter erreicht.",
        "L'altitude de densité maximale du capteur de l'enregistreur est de {} mètres, tu as atteint {} mètres.",
        "Maximale Druksensorhoogte van de logger is {} meter, je hebt {} meter bereikt.",
        "",
        "L'altitudine massima del sensore di pressione è: {}, raggiunta: {}",
    ],
    AVG_GNSS_ALT_CHANGE: [
        "Average GNSS altitude change between fixes in your file is {}, Minimum is {}.",
        "Durchschnittliche Differenz zwischen GNSS-Höhenwerten ist {}, Minimum sind {} Meter.",
        "La différence moyenne entre les données d'altitude GNSS est {}, le minimum est de {} mètres.",
        "De gemiddelde verandering van de GNSS-hoogte fixes in je bestand is {}, minimum is {}.",
        "",
        "La variazione di altitudine GNSS media tra le correzioni nel file è {}, il minimo è {}.",
    ],
    AVG_PRESS_ALT_CHANGE: [
        "Average pressure altitude change between fixes in your file is {}, Minimum is {}.",
        "Durchschnittliche Differenz zwischen Druck-Höhenwerten ist {}, Minimum sind {} Meter.",
        "La différence moyenne entre les données d'altitude de densité est {}, le minimum est de {} mètres.",
        "De gemiddelde verandering van de drukhoogte tussen fixes in je bestand is {}, minimum is {}.",
        "",
        "La variazione media dell'altitudine della pressione tra le correzioni nel file è {}, il minimo è {}.",
    ],
    HIGH_CHANGE_GNSS_ALT: [
        "{} high changes in GNSS altitude (more than {} m/s).",
        "{} hohe Wechsel der GNSS-Höhe (mehr als {} m/s).",
        "{} grands changements d'altitude GNSS (plus de {} m/s).",
        "{} grote veranderinen in je GPS-hoogte (meer dan {} m/s).",
        "",
        "{} variazioni elevate dell'altitudine GNSS (più di {} m / s).",
    ],
    HIGH_CHANGE_PRESS_ALT: [
        "{} high changes in pressure altitude (more than {} m/s).",
        "{} hohe Wechsel der Druck-Höhe (mehr als {} m/s).",
        "{} grands changements d'altitude de densité (plus de {} m/s).",
        "{} grote veranderinen in je drukhoogte (meer dan {} m/s).",
        "",
        "{} variazioni elevate dell'altitudine-pressione (più di {} m / s).",
    ],
    RAW_TIME_HARD_LIMIT_EXCEEDED: [
        "Hard time constraint ({} seconds) between fixes exceeded  at {}, interval without logging is {} seconds.",
        "Hartes Zeitlimit ({} Sekunden) zwischen GPS-Werten überschritten um {}, Spanne ohne Aufzeichnung sind {} Sekunden.",
        "Limite de temps 'dure' ({} secondes) entre les données de trace GPS dépassée de {}, la période de temps sans enregistrement de trace GPS est de {} secondes.",
        "Harde tijdsinterval ({} seconden) tussen fixes overschreden om {}, interval zonder log is {} seconden.",
        "",
        "Vincolo di tempo rigido ({} secondi) tra le correzioni superato in {}, l'intervallo senza registrazione è di {} secondi.",
    ],
    RAW_TIME_HARD_LIMIT_ALMOST_EXCEEDED: [
        "Hard time constraint ({} seconds) between fixes almost exceeded at {}, interval without logging is {} seconds.",
        "Hartes Zeitlimit ({} Sekunden) zwischen GPS-Werten beinahe überschritten um {}, Spanne ohne Aufzeichnung sind {} Sekunden.",
        "Limite de temps 'dure' ({} secondes) entre les données de trace GPS presque dépassée de {}, la période de temps sans enregistrement de trace GPS est de {} secondes.",
        "Harde tijdsinterval ({} seconden) tussen fixes bijna overschreden om {}, interval zonder log is {} seconden.",
        "",
        "Vincolo di tempo rigido ({} secondi) tra le correzioni quasi superato in {}, l'intervallo senza registrazione è di {} secondi.",
    ],
    RAW_TIME_HARD_LIMIT_EXCEEDED_OUTSIDE_SCORING: [
        "Hard time constraint ({} seconds) between fixes exceeded at {}, interval without logging is {} seconds.",
        "Hartes Zeitlimit ({} Sekunden) zwischen GPS-Werten überschritten um {}, Spanne ohne Aufzeichnung sind {} Sekunden.",
        "Limite de temps 'dure' ({} secondes) entre les données de trace GPS dépassée de {}, la période de temps sans enregistrement de trace GPS est de {} secondes.",
        "Harde tijdsinterval ({} seconden) tussen fixes overschreden om {}, interval zonder log is {} seconden.",
        "",
        "Vincolo di tempo rigido ({} secondi) tra le correzioni superato in {}, l'intervallo senza registrazione è di {} secondi.",
    ],
    RAW_TIME_SOFT_LIMIT_EXCEEDED: [
        "{} intervals exceed soft time limit between fixes ({}s), allowed {} intervals.",
        "{} Zeitintervalle zwischen Aufzeichnungen überschreiten das weiche Limit von {} Sekunden, erlaubt sind {} Intervalle.",
        "Intervalles de temps entre les enregistrements dépasse la limite de temps 'soft' de {} secondes, des intervalles de {} sont autorisés. ",
        "{} tijdsinterval overschrijd de zachte tijdslimiet tussen fixes ({}s), {} intervallen toegestaan.",
        "",
        "Gli intervalli {} superano il limite di tempo flessibile tra le correzioni ({}), gli intervalli {} consentiti.",
    ],
    NO_TAKEOFF: [
        "Did not detect takeoff.",
        "Start nicht erkannt.",
        "Le décollage n'a pas été reconnu",
        "Start niet herkend.",
        "",
        "Decollo non rilevato.",
    ],
    FIXES_BEFORE_TAKEOFF: [
        "Found {} fixes before takeoff, required are {}.",
        "{} Aufzeichnungen vor dem Start gefunden, nötig sind {}.",
        "{} Enregistrements trouvés avant le décollage, {} sont nécessaires.",
        "{} fixes gevonden vóór het opstijgen, {} fixes vereist.",
        "",
        "Trovate {} correzioni prima del decollo, obbligatorie sono {}.",
    ],
    NO_ENGINE_SENSOR: [
        "No engine sensor found, allowed engine sensors: {}.",
        "Kein Motorsensor gefunden, erlaubte Sensoren sind: {}.",
        "Pas de capteur de moteur trouvé, les capteurs autorisés sont: {}.",
        "Geen motorsensor gevonden, toegestane sensoren zijn: {}.",
        "",
        "Nessun sensore del motore trovato, sensori del motore consentiti: {}.",
    ],
    NO_FES_SENSOR: [
        "No FES sensor found, allowed FES sensors: {}.",
        "Kein FES Sensor gefunden, erlaubte Sensoren sind: {}.",
        "Pas de capteur FES trouvé, les capteurs autorisés sont: {}.",
        "Geen FES-sensor gevonden, toegestane sensoren zijn: {}.",
        "",
        "Nessun sensore FES trovato, sensori FES consentiti: {}.",
    ],
    NO_SCORING_WINDOWS: [
        "No scoring windows were found.",
        "Keine Wertungsfenster gefunden.",
        "Pas de fenêtre d'épreuve trouvée.",
        "Geen scoringvenster gevonden.",
        "",
        "Nessuna finestra di punteggio è stata trovata.",
    ]
}

export function i18nFlightErrors(key: keyof typeof translations, params: any[]): string {
    if (!translations[key]) console.error("Translation not found for", key);

    let template = translations[key][i18nStore.current];
    if (template === "") return translations[key][0]; // english
    for (const param of params) template = template.replace("{}", param);


    return template;
}
