import { i18nStore } from "@/shared/store"

// Main translation
export const translations = {
    // Scheme
    /*
    key: [
        "english",
        "german",
        "french",
        "dutch",
        "czech",
        "italian",
]
    */

    // Notification
    betaTitle: [
        "Prerelease",
        "Testversion",
        "",
        "Test versie",
        "",
        "Prerelease",
    ],
    betaText: [
        "Please be aware that we might need to delete data or break some functionality.",
        "Bitte sei dir bewusst, dass wir eventuell Daten löschen müssen oder Fehler auftauchen.",
        "",
        "Ben je ervan bewust dat data verloren kan gaan en sommige functies nog niet goed werken.",
        "",
        "Tieni presente che potrebbe essere necessario eliminare i dati o interrompere alcune funzionalità",
    ],
    waiting: [
        "Waiting",
        "Warten",
        "",
        "Wachtend",
        "",
        "In attesa",
    ],
    processing: [
        "Processing",
        "wird verarbeitet",
        "",
        "Wordt verwerkt",
        "",
        "In elaborazione",
    ],
    attention: [
        "Attention",
        "Achtung",
        "Attention",
        "Attentie",
        "",
        "Attenzione",
    ],
    success: [
        "Success",
        "Erfolg",
        "Avec succès",
        "Geslaagd",
        "",
        "Completato",
    ],
    errorAuthTitle: [
        "Session expired",
        "Sitzung abgelaufen",
        "",
        "Sessie vervallen",
        "",
        "Sessione scaduta",
    ],
    errorAuth: [
        "Please log in again",
        "Bitte logge dich erneut ein",
        "",
        "Log opniew in",
        "",
        "Effettua nuovamente l'accesso",
    ],
    errorServerTitle: [
        "Service unavailable",
        "Dienst nicht erreichbar",
        "",
        "Dienst niet beschikbaar",
        "",
        "Server temporaneamente non disponibile",
    ],
    errorServer: [
        "Please try again later or contact us",
        "Bitte versuche es später erneut oder kontaktiere uns",
        "",
        "Probeer het later nog eens",
        "",
        "Per favore, riprova più tardi o contattaci",
    ],
    errorForm: [
        "Please check your form inputs",
        "Bitte prüfe deine Formulareingaben",
        "",
        "Controleer het formulier",
        "",
        "Si prega di controllare gli input del modulo",
    ],
    verified: [
        "Email verification complete, please log in.",
        "E-Mail wurde verifiziert, bitte einloggen.",
        "Votre adresse e-mail a été vérifiée, veuillez vous connecter s'il vous plait.",
        "Verificatie gelukt, log nu in.",
        "",
        "Verifica dell'email completata, esegui l'accesso",
    ],
    notVerified: [
        "Please verify your Email first.",
        "Bitte verifiziere zuerst deine E-Mail.",
        "",
        "Verifieer je e-mailadres",
        "",
        "Verifica prima la tua email.",
    ],
    resetComplete: [
        "Password reset complete, please log in.",
        "Passwort wurde zurückgesetzt, bitte einloggen.",
        "Votre mot de passe a été réinitialisé, veuillez vous connecter s'il vous plait.",
        "Wachtwoord hersteld, log nu in.",
        "",
        "Reset della password completata, esegui l'accesso",
    ],
    info: [
        "Info",
        "Info",
        "",
        "Informatie",
        "",
        "Informazioni",
    ],
    warning: [
        "Warning",
        "Warnung",
        "",
        "Waarschuwing",
        "",
        "Attenzione",
    ],
    error: [
        "Error",
        "Fehler",
        "",
        "Fout",
        "",
        "Errore",
    ],
    analyzed: [
        "Analyzed",
        "Analyse",
        "",
        "Analyse",
        "",
        "Analizzato",
    ],

    // Aircraft
    aircraft: [
        "Aircraft",
        "Flugzeug",
        "Avion",
        "Vliegtuig",
        "",
        "Aereo",
    ],
    kind: [
        "Kind",
        "Art",
        "Sorte",
        "Soort",
        "",
        "Tipo",
    ],
    glider: [
        "Glider",
        "Segelflugzeug",
        "",
        "Zweefvliegtuig",
        "",
        "Aliante",
    ],
    fes: [
        "FES",
        "FES",
        "FES",
        "FES",
        "",
        "FES",
    ],
    engine: [
        "Engine",
        "Motor",
        "",
        "Motor",
        "",
        "Motore",
    ],
    paraglider: [
        "Paraglider",
        "Paragleiter",
        "",
        "Schermvlieger",
        "",
        "Parapendio",
    ],
    hangGlider: [
        "Hang Glider",
        "Drachen",
        "",
        "Deltavlieger",
        "",
        "Deltaplano",
    ],
    ulGlider: [
        "UL Glider",
        "UL Gleiter",
        "",
        "UL Zweefvliegtuig",
        "",
        "Aliante UL",
    ],
    family: [
        "Family",
        "Familie",
        "Famille",
        "Familie",
        "",
        "Famiglia",
    ],
    manufacturer: [
        "Manufacturer",
        "Hersteller",
        "Fabricant",
        "Fabrikant",
        "",
        "Produttore",
    ],
    seats: [
        "Seats",
        "Sitze",
        "Places",
        "Zitplaatsen",
        "",
        "Posti a sedere",
    ],
    class: [
        "Class",
        "Klasse",
        "Classe",
        "Klasse",
        "",
        "Classe",
    ],
    index: [
        "Index",
        "Index",
        "",
        "Index",
        "",
        "Index",
    ],
    igc: [
        "IGC",
        "IGC",
        "IGC",
        "IGC",
        "",
        "IGC",
    ],

    // Airport
    airport: [
        "Airport",
        "Flughafen",
        "Aéroport",
        "Vliegveld",
        "",
        "Aereoporto",
    ],
    airports: [
        "Airports",
        "Flughäfen",
        "",
        "Vliegvelds",
        "",
        "Aereoporti",
    ],
    radio: [
        "Radio",
        "Funk",
        "Radio",
        "Radio",
        "",
        "Radio",
    ],
    frequency: [
        "Frequency",
        "Frequenz",
        "Fréquence",
        "Frequentie",
        "",
        "Frequenza",
    ],
    description: [
        "Description",
        "Beschreibung",
        "Description",
        "Omschrijving",
        "",
        "Descrizione",
    ],
    type: [
        "Type",
        "Typ",
        "Type",
        "Type",
        "",
        "Tipo",
    ],
    category: [
        "Category",
        "Kategorie",
        "Catégorie",
        "Categorie",
        "",
        "Categoria",
    ],
    location: [
        "Location",
        "Standort",
        "",
        "Lokatie",
        "",
        "Posizione",
    ],
    timezone: [
        "Timezone",
        "Zeitzone",
        "",
        "Tijdzone",
        "",
        "Fuso orario",
    ],
    region: [
        "Region",
        "Region",
        "Région",
        "Regio",
        "",
        "Regione",
    ],
    elevation: [
        "Elevation",
        "Höhe",
        "Élévation",
        "Hoogte",
        "",
        "Elevazione",
    ],
    usage: [
        "Usage",
        "Nutzung",
        "",
        "Gebruik",
        "",
        "Utilizzo",
    ],
    coordinates: [
        "Coordinates",
        "Koordinaten",
        "Coordonnées",
        "Coördinaten",
        "",
        "Coordinate",
    ],
    latitudeAbbrev: [
        "Lat.",
        "Lat.",
        "",
        "Lat.",
        "",
        "Lat.",
    ],
    longitudeAbbrev: [
        "Lon.",
        "Lon.",
        "",
        "Lon.",
        "",
        "Lon.",
    ],
    runway: [
        "Runway",
        "Piste",
        "",
        "Baan",
        "",
        "Pista di decollo",
    ],
    length: [
        "Length",
        "Länge",
        "",
        "Lengte",
        "",
        "Lunghezza",
    ],
    width: [
        "Width",
        "Breite",
        "",
        "Breedte",
        "",
        "Altezza",
    ],
    surface: [
        "Surface",
        "Oberfläche",
        "",
        "Soort",
        "",
        "Superficie",
    ],
    strength: [
        "Strength",
        "Stärke",
        "",
        "Sterkte",
        "",
        "Potenza",
    ],
    glidingUsage: [
        "Gliding Usage",
        "Segelflugnutzung",
        "",
        "Zweefvliegterrein",
        "",
        "Piano di volo",
    ],
    reign: [
        "Reign",
        "Einflussgebiet",
        "",
        "Invloedgebied",
        "",
        "Area di influenza",
    ],
    launches: [
        "Gliding launches",
        "Segelflugstarts",
        "",
        "Zweefvliegstarts",
        "",
        "Decolli di alianti",
    ],

    // Call to action
    reportFalseInformation: [
        "Report false information",
        "Melde falsche Informationen",
        "Signale fausses informations",
        "Meld verkeerde informatie",
        "",
        "Segnala informazioni false",
    ],
    logIn: [
        "Log in",
        "Einloggen",
        "Se connecter",
        "Inloggen",
        "",
        "Accedi",
    ],
    signUp: [
        "Sign up",
        "Registrieren",
        "S'inscrire",
        "Registreren",
        "",
        "Registrati",
    ],
    forgotPassword: [
        "Forgot Password?",
        "Passwort vergessen?",
        "Mot de passe oublié?",
        "Wachtwoord vergeten?",
        "",
        "Password dimenticata?",
    ],
    verifyEmail: [
        "Send verification link again",
        "Sende Verifizierungslink erneut",
        "",
        "Verstuur verificatie e-mail nogmaals",
        "",
        "Invia di nuovo il link di verifica",
    ],
    changePassword: [
        "Change Password",
        "Passwort ändern",
        "Changer mon mot de passe",
        "Wachtwoord veranderen",
        "",
        "Cambia password",
    ],
    resendVerification: [
        "Send verification link",
        "Verifizierungslink senden",
        "",
        "Verificatie e-mail versturen",
        "",
        "Invia link di verifica",
    ],
    sendEmailAgain: [
        "Send email again",
        "E-Mail erneut senden",
        "Envoyer l'email à nouveau",
        "Email nogmaals versturen",
        "",
        "Invia email di nuovo",
    ],
    showStories: [
        "Show stories",
        "Zeige Geschichten",
        "",
        "Laat verhalen zien",
        "",
        "Mostra storie",
    ],
    showAllArticles: [
        "Show all articles",
        "Zeige alle Artikel",
        "",
        "Laat alle artikelen zien",
        "",
        "Mostra tutti gli articoli",
    ],
    showLatest: [
        "Show latest",
        "Zeige Neueste",
        "",
        "Laatste bekijken",
        "",
        "Mostra le ultime",
    ],
    showDaily: [
        "Show daily",
        "Zeige Tagesbeste",
        "",
        "Beste bekijken",
        "",
        "Mostra articoli giornalieri",
    ],
    cancel: [
        "Cancel",
        "Abbrechen",
        "Annuler",
        "Annuleer",
        "",
        "Cancella",
    ],
    save: [
        "Save",
        "Speichern",
        "",
        "Opslaan",
        "",
        "Salva",
    ],
    edit: [
        "Edit",
        "Bearbeiten",
        "",
        "Aanpassen",
        "",
        "Modifica",
    ],
    delete: [
        "Delete",
        "Löschen",
        "",
        "Verwijderen",
        "",
        "Elimina",
    ],
    show: [
        "show",
        "zeigen",
        "",
        "laten zien",
        "",
        "Mostra",
    ],

    // Flight
    flight: [
        "Flight",
        "Flug",
        "",
        "Vlucht",
        "",
        "Volo",
    ],
    flights: [
        "Flights",
        "Flüge",
        "",
        "Vluchten",
        "",
        "Voli",
    ],
    allFlights: [
        "All flights",
        "Alle Flüge",
        "Tous les vols",
        "Alle vluchten",
        "",
        "Tutti i voli",
    ],
    flightDeleted: [
        "Flight deleted",
        "Flug gelöscht",
        "",
        "Vlucht verwijderd",
        "",
        "Volo Cancellato",
    ],
    flightSaved: [
        "Flight saved",
        "Flug gespeichert",
        "",
        "Vlucht opgeslagen",
        "",
        "Volo salvato",
    ],
    flightDeleteConfirm: [
        "Do you really want to delete this flight?",
        "Möchtest du diesen Flug wirklich löschen?",
        "",
        "Wil je deze vlucht echt verwijderen?",
        "",
        "Vuoi veramente cancellare questo volo?",
    ],

    // User
    junior: [
        "Junior",
        "Junior*in",
        "",
        "Junior",
        "",
        "Bambini",
    ],
    male: [
        "Male",
        "Männlich",
        "Masculin",
        "Man",
        "",
        "Maschi",
    ],
    female: [
        "Female",
        "Weiblich",
        "Féminin",
        "Vrouw",
        "",
        "Femmine",
    ],
    other: [
        "Other",
        "Divers",
        "Sexe neutre",
        "Anders",
        "",
        "Altro",
    ],
    pilots: [
        "Pilots",
        "Pilot*innen",
        "",
        "Vlieger",
        "",
        "Piloti",
    ],

    // Meeting
    openFlight: [
        "Open flight",
        "Flug öffnen",
        "",
        "Vlucht openen",
        "",
        "Apri il volo",
    ],
    compare: [
        "Compare",
        "Vergleichen",
        "",
        "Vergelijken",
        "",
        "Confronta",
    ],
    remove: [
        "Remove",
        "Entfernen",
        "",
        "Verwijderen",
        "",
        "Rimuovi",
    ],

    // Task kind
    FR: [
        "Free",
        "Frei",
        "",
        "Vrije",
        "",
        "Senza",
    ],
    FR4: [
        "Free (DMSt)",
        "Frei (DMSt)",
        "",
        "Vrije (DMSt)",
        "",
        "Senza (DMSt)"
    ],
    GL: [
        "Goal",
        "Ziel",
        "",
        "Doel",
        "",
        "Obiettivo",
    ],
    TR: [
        "Triangle",
        "Dreieck",
        "",
        "Driehoek",
        "",
        "Triangolo",
    ],
    RT: [
        "Rectangle",
        "Viereck",
        "",
        "",
        "",
        "Rettangolo",
    ],
    OR: [
        "Out and Return",
        "Zielrück",
        "",
        "Retour",
        "",
        "Ritorno",
    ],
    closed: [
        "Closed",
        "Geschlossen",
        "",
        "GEsloten",
        "",
        "Chiuso",
    ],
    open: [
        "Open",
        "Offen",
        "",
        "Open",
        "",
        "Aperto",
    ],
    unnamed: [
        "Unnamed",
        "Unbenannt",
        "",
        "Zonder naam",
        "",
        "Senza nome",
    ],

    // Form fields
    email: [
        "Email",
        "E-Mail",
        "Adresse e-mail",
        "Email",
        "",
        "Email",
    ],
    password: [
        "Password",
        "Passwort",
        "Mot de passe",
        "Wachtwoord",
        "",
        "Password",
    ],
    name: [
        "First and last name",
        "Vor- und Nachname",
        "Prénom et Nom",
        "Voor- en Achternaam",
        "",
        "Nome e Cognome",
    ],
    birthdate: [
        "Date of birth",
        "Geburtsdatum",
        "Date de naissance",
        "Geboortedatum",
        "",
        "Data di nascita",
    ],
    dateFormat: [
        "e.g. 1960-01-25 (YYYY-MM-DD)",
        "z.B. 1960-01-25 (JJJJ-MM-DD)",
        "",
        "b.v. 1960-01-25 (JJJJ-MM-DD)",
        "",
        "es. 1960-01-25 (YYYY-MM-DD)",
    ],
    club: [
        "Club",
        "Verein",
        "Club",
        "Club",
        "",
        "Club",
    ],
    textConfirm: [
        "I have read and agree to the following documents:",
        "Ich habe die folgenden Dokumente gelesen und stimme zu:",
        "",
        "Ik heb de volgende documenten gelezen en ga akkoord:",
        "",
        "Ho letto e accetto i seguenti documenti:",
    ],
    privacyPolicy: [
        "Privacy Policy",
        "Datenschutzerklärung",
        "",
        "Privacy Statement",
        "",
        "Politica sulla Privacy",
    ],
    userAgreement: [
        "User Agreement",
        "Nutzungsbedingungen",
        "",
        "Voorwaarden",
        "",
        "Accordo per gli utenti",
    ],
    subscribeNewsletter: [
        "Subscribe to our newsletter",
        "Abonniere unseren Newsletter",
        "Abonne-toi à notre newsletter",
        "Meld je aan voor de nieuwsbrief",
        "",
        "Iscriviti alla nostra Newsletter",
    ],
    newPassword: [
        "New password",
        "Neues Passwort",
        "Nouveau mot de passe",
        "Nieuw wachtwoord",
        "",
        "Nuova password",
    ],
    registration: [
        "Registration (optional)",
        "Registrierung (optional)",
        "",
        "Registreren (niet verpflicht)",
        "",
        "Registrazione (opzionale)",
    ],
    coPilotName: [
        "Co-Pilot name",
        "Name Co-Pilot*in",
        "",
        "Tweede vlieger",
        "",
        "Nome copilota",
    ],
    coPilotDateOfBirth: [
        "Co-Pilot date of birth",
        "Co-Pilot Geburtsdatum",
        "",
        "Geboorte datum tweede vlieger",
        "",
        "Data di nascita del copilota",
    ],
    competitionId: [
        "Competition ID (optional)",
        "Wettbewerbs-ID (optional)",
        "",
        "Wedstrijdnummer (niet verpflicht)",
        "",
        "ID Concorenza (opzionale)",
    ],

    // Authentication
    joinThanks: [
        "Thank you for joining WeGlide!",
        "Wir freuen uns dich in der Community zu begrüßen!",
        "Merci d'avoir rejoint WeGlide!",
        "Bedankt voor je aanmelding bij WeGlide!",
        "",
        "Grazie per esserti unito a WeGilde!",
    ],
    urgeVerify: [
        "Please verify your email by clicking the link in the email you got.",
        "Bitte verifiziere deine E-Mail Adresse über den Link den wir dir zugesendet haben.",
        "Merci de vérifier ton adresse e-mail en cliquant sur le lien que nous t'avons envoyé ",
        "Verifieer je email adres door op de link te klikken die we je net hebben gestuurd.",
        "",
        "Per favore verifica la tua email cliccando il link che ti è arrivato nella tua email",
    ],
    verifyInstructions: [
        "If not you got no email, please wait a minute and check your spam folder or contact us at",
        "Falls du keine E-Mail bekommen hast, warte eine Minute und prüfe deinen Spam-Ordner oder kontaktiere uns unter",
        "Si tu n'as pas recu de mail, attends une minute et regarde dans tes spams ou contactes nous",
        "Als je geen mail het gehad, wacht een paar minuten, controleer je spam folder of stuur ons een bericht.",
        "",
        "Se non hai ricevuto nessuna email, per favore aspetta un minuto e controlla la posta indesiderata o contattaci a",
    ],
    joinCommunity: [
        "Join the community!",
        "Werde Teil der Community!",
        " 	Rejoins la communauté!",
        "Neem deel aan WeGlide!",
        "",
        "Unisciti alla community!",
    ],
    errorPrivacy: [
        "Please accept our privacy statements and terms.",
        "Bitte akzeptiere die Nutzungsbedingungen und Datenschutzerklärung.",
        "Merci d'accepter les conditions d'utilisation et la déclaration de confidentialité.",
        "Accepteer onze voorwaarden en het privacy statement.",
        "",
        "Per favore accetta le nostre normative sulla privacy e i termini.",
    ],
    errorCaptcha: [
        "Please solve the captcha to verify you are human.",
        "Bitte löse das Captcha um zu zeigen dass du ein Mensch bist.",
        "",
        "Los de Captcha op om zeker te zijn dat je geen robot bent.",
        "",
        "Si prega di risolvere il captcha per verificare che non sei un robot",
    ],
    verifying: [
        "Verifying Email",
        "E-Mail wird verifiziert",
        "Nous vérifions ton adresse e-mail",
        "Email wordt geverifieerd",
        "",
        "Verificando l'email",
    ],
    urgeLogIn: [
        "Please log in afterwards",
        "Danach bitte einloggen",
        "Ensuite merci de vous connecter",
        "Daarna inloggen",
        "",
        "Puoi effettuare il login",
    ],
    requestVerification: [
        "Request new verification link",
        "Neuen Verifizierungslink anfordern",
        "",
        "Vraag nieuwe verificatie link aan",
        "",
        "Richiedi un nuovo link di verifica",
    ],
    requestRecoverPassword: [
        "Request password recovery",
        "Passwort-Wiederherstellung anfordern",
        "Demander la récupération de mon mot de passe",
        "Wachtwoord herstel aanvragen",
        "",
        "Richiedi password di recupero",
    ],
    instructionsEmailed: [
        "Email send, please follow the mailed instructions.",
        "E-Mail gesendet, bitte folge den dort beschriebenen Anweisungen",
        "Nous vous avons envoyé un mail avec les instructions à suivre pour récupérer votre mot de passe",
        "Email verstuurd",
        "",
        "Email inviata, segui le istruzioni al suo interno",
    ],
    recoverPassword: [
        "Recover password",
        "Passwort Wiederherstellen",
        "récupérer mon mot de passe",
        "Wachtwoord herstellen",
        "",
        "Password di recupero",
    ],
    choosePassword: [
        "Choose new password",
        "Wähle ein neues Passwort",
        "Choisir un nouveau mot de passe",
        "Stel een nieuw wachtwoord in",
        "",
        "Scegli una nuova password",
    ],
    resetInvalid: [
        "Password recovery link is no longer valid. Please request a new one.",
        "Link zur Passwort-Wiederherstellung ist abgelaufen. Bitte fordere einen neuen an.",
        "Le lien pour récupérer ton mot de passse est éxpiré. Merci d'en demander un nouveau.",
        "Wachtwoord herstel link is niet meer geldig. Vraag een nieuwe aan.",
        "",
        "Il link per il recupero della password non è piu valido. Richiedine uno nuovo",
    ],

    // Airspace
    airspace: [
        "Airspace",
        "Luftraum",
        "",
        "Luchtruim",
        "",
        "Spazio aereo",
    ],
    airspaces: [
        "Airspaces",
        "Lufträume",
        "",
        "Luchtruimen",
        "",
        "Spazi aerei",
    ],
    noAirspaceViolations: [
        "No airspaces crossed.",
        "Keine Lufträume durchflogen.",
        "",
        "Geen luchtruim schendingen.",
        "",
        "Nessuno spazio aereo incrociato",
    ],

    // Page not found
    pageNotFound: [
        "Landing site not found",
        "Ort zum Landen nicht gefunden",
        "",
        "Pagina niet gevonden",
        "",
        "Pagina non trovata",
    ],
    pickMeUp: [
        "Pick me up",
        "Bring mich zurück",
        "",
        "Breng me terug",
        "",
        "Torna indietro",
    ],

    // Filter
    filterPlaceholder: [
        "Search",
        "Suche",
        "",
        "Zoeken",
        "",
        "Cerca",
    ],

    // Flight detail
    flightDetail: [
        "Flight detail",
        "Flugdetails",
        "",
        "Vluchtdetails",
        "",
        "Dettagli del volo",
    ],
    wingmen: [
        "Wingmen",
        "Gefährten",
        "",
        "Wingmen",
        "",
        "Amici",
    ],
    scoreProcessing: [
        "Scoring in process",
        "Punkte werden berechnet,",
        "",
        "Bezig met scoren",
        "",
        "Calcondo i punti".
    ],
    pleaseReload: [
        "please reload this page.",
        "bitte lade die Seite neu.",
        "",
        "herlaad deze pagina.",
        "",
        "Per favore ricarica la pagina.",
    ],
    points: [
        "Points",
        "Punkte",
        "",
        "Punten",
        "",
        "Punti",
    ],
    invalid: [
        "Invalid",
        "Ungültig",
        "",
        "Ongeldig",
        "",
        "Non valido",
    ],
    invalidFlight: [
        "Flight claimed too late for this contest",
        "Flugmeldung zu spät für diese Wertung",
        "",
        "Vlucht te laat ingediend voor deze wedstrijd",
        "",
        "Il volo è stato richiesto troppo tardi per questo concorso",
    ],
    free: [
        "Free",
        "Frei",
        "",
        "Vrije",
        "",
        "Gratuito",
    ],
    speed: [
        "Speed",
        "Geschwindigkeit",
        "",
        "Snelheid",
        "",
        "Velocità",
    ],
    triangle: [
        "Triangle",
        "Dreieck",
        "",
        "Driehoek",
        "",
        "Triangolo",
    ],
    rectangle: [
        "Rectangle",
        "Viereck",
        "",
        "Vierhoek",
        "",
        "Rettangolo",
    ],
    declared: [
        "Declared",
        "Deklariert",
        "",
        "Gedeclareerd",
        "",
        "Dichiarato",
    ],
    outReturn: [
        "Out and Return",
        "Zielrück",
        "",
        "Retour",
        "",
        "Ritorno",
    ],
    convexHull: [
        "Convex Hull",
        "Konvexe Hülle",
        "",
        "Convex omhulsel",
        "",
        "Scafo convesso",
    ],
    teSpeed: [
        "EC Speed",
        "EK Geschwindigkeit",
        "",
        "TE Snelheid",
        "",
        "Velocità ER",
    ],
    teSpeedDescription: [
        "Energy Compensated Speed relative to task",
        "Energiekompensierte Geschwindigkeit relativ zur Aufgabe",
        "",
        "Endergie gecompenseerde snelheid i.r.t. opdracht",
        "",
        "Velocità compensata dall'energia relativa al compito",
    ],
    declaredTask: [
        "Declared Task",
        "Deklarierte Aufgabe",
        "",
        "Gedeclareerde opdracht",
        "",
        "Incarichi dichiarati",
    ],
    declaredTaskDescription: [
        "Task declared by pilot before flight",
        "Vom Piloten vor dem Flug deklarierte Aufgabe",
        "",
        "De opdracht die voor de vlucht is gedeclareed",
        "",
        "Incarichi dichiarati dal pilota prima del volo",
    ],
    statistics: [
        "Statistics",
        "Statistiken",
        "",
        "Statistieken",
        "",
        "Statistiche",
    ],
    general: [
        "General",
        "Allgemein",
        "",
        "Algemeen",
        "",
        "Generale",
    ],
    distanceAbbrev: [
        "Dist.",
        "Dist.",
        "",
        "Afst.",
        "",
        "Dist.",
    ],
    windAbbrev: [
        "Wind",
        "Wind",
        "",
        "Wind",
        "",
        "Vento",
    ],
    speedAbbrev: [
        "Speed",
        "V",
        "V",
        "V",
        "",
        "V",
    ],
    electric: [
        "Electric",
        "Elektrisch",
        "",
        "Electrisch",
        "",
        "Elettricità",
    ],
    energyAbbrev: [
        "Energy",
        "Energie",
        "",
        "Energie",
        "",
        "Energia",
    ],
    total: [
        "Total",
        "Gesamt",
        "",
        "Totaal",
        "",
        "Totale",
    ],
    thermaling: [
        "Thermaling",
        "Thermik",
        "",
        "Thermiek",
        "",
        "Termico",
    ],
    countAbbrev: [
        "Count",
        "Anzahl",
        "",
        "Aantal",
        "",
        "Numero",
    ],
    timeAbbrev: [
        "Time",
        "Zeit",
        "",
        "Tijd",
        "",
        "Tempo",
    ],
    averageAbbrev: [
        "Avg.",
        "Schnitt",
        "",
        "Gem.",
        "",
        "Media",
    ],
    glide: [
        "Glide",
        "Gleiten",
        "",
        "Glijden",
        "",
        "Planare",
    ],
    ratioAbbrev: [
        "Ratio",
        "Ratio",
        "",
        "Ratio",
        "",
        "Rapporto",
    ],
    detourAbbrev: [
        "Detour",
        "Umweg",
        "",
        "Omweg",
        "",
        "Deviazione",
    ],
    distance: [
        "Distance",
        "Distanz",
        "",
        "Afstand",
        "",
        "Distanza",
    ],
    duration: [
        "Duration",
        "Dauer",
        "",
        "Duur",
        "",
        "Durata",
    ],
    takeoff: [
        "Takeoff",
        "Start",
        "",
        "Start",
        "",
        "Partenza",
    ],
    landing: [
        "Landing",
        "Landung",
        "",
        "Landing",
        "",
        "Atterraggio",
    ],
    status: [
        "Status",
        "Status",
        "",
        "Status",
        "",
        "Stato",
    ],
    flightValid: [
        "flight valid",
        "Flug gültig",
        "",
        "Geldige vlucht",
        "",
        "Volo valido",
    ],
    flightInvalid: [
        "flight invalid",
        "Flug ungültig",
        "",
        "Ongeldige vlucht",
        "",
        "Volo non valido",
    ],
    flightPending: [
        "flight pending",
        "Flug ausstehend",
        "",
        "Vlucht in afwachting",
        "",
        "Volo in attesa",
    ],
    filePending: [
        "file pending",
        "Datei ausstehend",
        "",
        "Bestand in afwachting",
        "",
        "File in attesa",
    ],
    fileHashValid: [
        "file hash valid",
        "Dateihash gültig",
        "",
        "Datahash geldig",
        "",
        "Hash del file valido",
    ],
    fileIgcValid: [
        "interim IGC valid",
        "Vorläufig IGC valide",
        "",
        "IGC data geldig",
        "",
        "CIG provvisoria valida",
    ],
    fileInvalid: [
        "file interim invalid",
        "Datei vorläufig ungültig",
        "",
        "Data ongeldig",
        "",
        "File non valido",
    ],
    comment: [
        "Comment (optional)",
        "Kommentar (optional)",
        "",
        "Opmerkingen (niet verplicht)",
        "",
        "Commento (opzionale)",
    ],
    outstart: [
        "Outstart",
        "Außenstart",
        "",
        "Buitenstart",
        "",
        "outstart",
    ],
    outlanding: [
        "Outlanding",
        "Außenlandung",
        "",
        "Buitenlanding",
        "",
        "outlanding",
    ],
    fileValid: [
        "No remarks analyzing this flight.",
        "Keine Anmerkungen zur Analyse des Fluges.",
        "",
        "",
        "",
        "Nessuna osservazione analizzando questo volo.",
    ],
    loggerInformation: [
        "Logger information",
        "Logger Informationen",
        "",
        "Logger informatie",
        "",
        "Registro informazioni",
    ],
    share: [
        "Share",
        "Teilen",
        "",
        "Delen",
        "",
        "Condividi",
    ],
    embed: [
        "Embed",
        "Einbetten",
        "",
        "Integreren",
        "",
        "Embed",
    ],
    showBarogram: [
        "Show barogram",
        "Barogram zeigen",
        "",
        "Laat barogram zien",
        "",
        "Mostra barogramma",
    ],
    includeBBox: [
        "Current bounding box",
        "Aktueller Ausschnitt",
        "",
        "Actuele uitsnede",
        "",
        "Riquadro di delimitazione",
    ],
    displayedFlights: [
        "Displayed flights",
        "Angezeigte Flüge",
        "",
        "Zichtbare vluchten",
        "",
        "Voli visualizzati",
    ],
    similarFlights: [
        "Similar flights",
        "Ähnliche Flüge",
        "",
        "Gelijke vluchten",
        "",
        "Voli simili",
    ],

    // Flight list
    flightList: [
        "Flight list",
        "Flugliste",
        "",
        "Vluchtenlijst",
        "",
        "Elenco dei voli",
    ],
    flightOverviewSwitch: [
        "Map",
        "Karte",
        "",
        "Kaart",
        "",
        "Mappa",
    ],
    date: [
        "Date",
        "Datum",
        "",
        "Datum",
        "",
        "Data",
    ],
    pilot: [
        "Pilot",
        "Pilot",
        "",
        "Vlieger",
        "",
        "Pilota",
    ],
    more: [
        "More",
        "Mehr",
        "",
        "Meer",
        "",
        "Altro",
    ],
    noFlightsFilter: [
        "No flights with these filters.",
        "Keine Flüge mit diesen Filtern.",
        "",
        "Geen resultaten met deze filter",
        "",
        "Nessun volo con questi filtri",
    ],

    // Flight overview
    flightOverview: [
        "Flight overview",
        "Flugübersicht",
        "",
        "Overzicht",
        "",
        "Panoramica volo",
    ],
    flightListSwitch: [
        "List",
        "Liste",
        "",
        "Lijst",
        "",
        "Lista",
    ],

    // Upload/Edit
    uploadFlights: [
        "Upload flights",
        "Flüge hochladen",
        "",
        "Vlucht uploaden",
        "",
        "Carica volo",
    ],
    editFlight: [
        "Edit flight",
        "Flug bearbeiten",
        "",
        "VLucht aanpassen",
        "",
        "Modifica volo",
    ],

    // Form edit flight
    scoringReset: [
        "Reset scoring windows",
        "Wertungsfenster zurücksetzen",
        "",
        "Scoringsgebied herstellen",
        "",
        "Resetta punteggi",
    ],
    scoringAdd: [
        "Add scoring window",
        "Neues Wertungsfenster",
        "",
        "Scoringsgebied toevoegen",
        "",
        "Aggiungi punteggio",
    ],
    scoringStart: [
        "Scoring start",
        "Wertungsbeginn",
        "",
        "Begin van het scoren",
        "",
        "Inizio punteggio",
    ],
    scoringEnd: [
        "Scoring end",
        "Wertungsende",
        "",
        "Eind van het scoren",
        "",
        "Fine punteggio",
    ],
    registrationFormat: [
        "Only uppercase letters, numbers and '-' are allowed for registration.",
        "Nur Großbuchstaben, Ziffern und '-' sind die Registrierung erlaubt.",
        "",
        "Alleen hoofdletters, nummers en '-' zijn toegestaan voor registratie.",
        "",
        "Sono accettati solo lettere maiuscole, numeri e '-' per la registrazione. ",
    ],
    isNotRegistered: [
        "is not registered, no further authentication required.",
        "ist nicht registriert, keine Authentifizierung erforderlich.",
        "",
        "is niet geregistreerd, geen verdere authenticatie benodigd.",
        "",
        "non è registrato, non è richiesta alcuna ulteriore autenticazione.",
    ],
    isRegistered: [
        "is registered, date of birth required as authentication.",
        "ist registriert, Geburtsdatum wird als Authentifizierung benötigt.",
        "",
        "is geregistreed, geboortedatum vereist voor authenticatie.",
        "",
        "è registrato, la data di nascita è richiesta come autenticazione",
    ],
    competitionIdFormat: [
        "Only alphanumeric characters are allowed for competition id.",
        "Nur Alphanumerische Zeichen sind für die Wettbewerbs-ID erlaubt.",
        "",
        "Alleen alfanumerieke karakters zijn toegestaan als wedstrijdnummer.",
        "",
        "Sono accettati sono caratteri alfanumerici per l' ID Concorenza",
    ],
    scoringWindows: [
        "Scoring windows",
        "Wertungsfenster",
        "",
        "Scoringsgebied",
        "",
        "Finestra punteggi",
    ],
    scoringTowingNotice: [
        "Please make sure that the scoring windows do not include towing.",
        "Bitte prüfe, dass die Wertungsfenster kein Schleppen beinhalten.",
        "",
        "Sleeptijd mag geen onderdeel zijn van het scoringsgebied.",
        "",
        "Assicurati che le finestre di punteggio non includano il rimorchio",
    ],
    scoringiNotice: [
        "Airplane with electric propulsion selected. Please make sure time spans with running engine (yellow) are excluded from scoring.",
        "Flugzeug mit elektrischem Antrieb ausgewählt. Bitte prüfe, dass die Wertungsfenster keinen Motorlauf (gelb) beinhalten.",
        "",
        "Vliegtuig met electro motor geselecteerd, het scoringsgebied mag geen motorlooptijd bevatten.",
        "",
        "Aereo con propulsione elettrica selezionato. Assicurati che i periodi di tempo con il motore in funzione (giallo) siano escusi dal punteggio",
    ],
    scoringEngineNotice: [
        "Airplane with engine selected. Please make sure time spans with running engine (yellow) are excluded from scoring.",
        "Flugzeug mit Motor ausgewählt. Bitte prüfe, dass die Wertungsfenster keinen Motorlauf (gelb) beinhalten.",
        "",
        "Vliegtuig met motor geselecteerd, het scoringgebied mag geen motorlooptijd bevatten.",
        "",
        "Aereo con motore selezionato, Assicurati che i periodi di tempo con il motore in funzione (giallo) siano escusi dal punteggio",
    ],
    errorTerms: [
        "Please agree to the terms.",
        "Bitte stimme den Bedingungen zu.",
        "",
        "Ga eerst akkoord met de voorwaarden.",
        "",
        "Per favore accetta i termini.",
    ],
    textConfirmUpload: [
        "I confirm that my scoring windows are chosen according to the rules,\
         each active airspace crossed was cleared by ATC\
         and I have read and accepted the following documents:",
        "Ich bestätige, dass ich die Wertungsfenster nach den Regeln gewählt habe, \
         jeder durchflogene aktive Luftraum von ATC freigegeben wurde,\
         und ich die folgenden Dokumente gelesen habe und ihnen zustimme:",
        "",
        "Ik bevestig dat mijn scoringsgebied(en) zijn geslecteerd volgens de regels,\
        voor elk luchtruimbeperking had ik ATC-klaring\
        en ik heb de volgende documenten gelezen en ga akkoord:",
        "",
        "Confermo che le mie finestre di punteggio sono scelte in base alle regole \
         che ogni spazio aereo attivo attraversato è stato cancellato dall'ATC e \
          ho letto e accettato i seguenti documenti:",
    ],

    // Form upload igc
    hello: [
        "Hello",
        "Hallo",
        "Bonjour",
        "Hallo",
        "",
        "Ciao",
    ],
    shareFlights: [
        "share your flights!",
        "teile deine Flüge!",
        "",
        "deel je vluchten!",
        "",
        "condividi i tuoi voli!",
    ],
    unauthorizedNotice: [
        "You are not logged in, please provide your date of birth and full name to upload if you have an account or",
        "Du bist nicht eingeloggt, bitte gib deinen vollen Namen sowie dein Geburtsdatum zum Hochladen an falls du einen Account hast oder",
        "",
        "Je bent niet ingelogd. Vul je volledige naam en geboortedatum in.",
        "",
        "Non hai effettuato l'accesso, per favore fornisci la tua data di nascita e il tuo nome completo se hai un account o",
    ],
    logInFirst: [
        "log in",
        "melde dich an",
        "",
        "log in",
        "",
        "log in",
    ],
    igcDragText: [
        "Drag .igc files here to upload or click to select",
        "Ziehe IGC-Dateien hierher zum Hochladen oder klicke zum Auswählen",
        "",
        "Sleep je .igc-bestanden hierheen om ze te uploaden of klik hier om ze te slecteren",
        "",
        "Trascina i file .igc qua per effettuare l'upload o clicca per selezionarli",
    ],
    igcDropText: [
        "Drop .igc files to upload",
        "Lasse die IGC-Dateien los zum Hochladen",
        "",
        "Laat je .igc-bestenden los om ze te uploaden",
        "",
        "Rilascia il file .igc",
    ],

    // Teaser
    currentLanguage: [
        "English",
        "Deutsch",
        "Français",
        "Nederlands",
        "",
        "Italian",
    ],
    welcome: [
        "Welcome",
        "Willkommen",
        "",
        "Welkom",
        "",
        "Benvenuto",
    ],
    shareAdventures: [
        "Share your latest adventures.",
        "Teile deine neuesten Abenteuer.",
        "",
        "Deel je laatste avonturen",
        "",
        "Condividi le tue ultime avventure",
    ],
    uploadFlight: [
        "Upload flight",
        "Flug hochladen",
        "",
        "Vluchten uploaden",
        "",
        "Carica un volo",
    ],
    myProfile: [
        "My profile",
        "Mein Profil",
        "",
        "Mijn profiel",
        "",
        "Il mio profilo",
    ],
    encourage: [
        "Let's take off together and join the next-generation gliding platform.",
        "Lass uns zusammen abheben und genieße die Segelflugplattform der nächsten Generation.",
        "",
        "Laten we samen starten en sluit je aan bij het zweefplatform van de volgende generatie.",
        "",
        "Decolliamo insieme e unisciti alla nuova piattaforma di volo.",
    ],
    fromByPilots: [
        "Built by Pilots for Pilots.",
        "Entworfen von Piloten für Piloten.",
        "",
        "Gebouwd voor en door vliegers.",
        "",
        "Costruito da piloti per piloti",
    ],

    // Partner
    partner: [
        "Partner",
        "Partner",
        "",
        "Partner",
        "",
        "Partner",
    ],
    sponsors: [
        "Funded by",
        "Gefördert durch",
        "",
        "Mede mogelijk gemaakt door",
        "",
        "Fondato da",
    ],
    logoLang: [
        "EN",
        "DE",
        "EN",
        "EN",
        "",
        "IT",
    ],

    // Footer
    about: [
        "About",
        "Über",
        "",
        "Over",
        "",
        "Riguardo a noi",
    ],
    contact: [
        "Contact",
        "Kontakt",
        "",
        "Contact",
        "",
        "Contatti",
    ],
    philosophy: [
        "Philosophy",
        "Philosophie",
        "",
        "Filosofie",
        "",
        "Filosofia",
    ],
    imprint: [
        "Imprint",
        "Impressum",
        "",
        "Colofon",
        "",
        "Impronta",
    ],
    media: [
        "Media",
        "Medien",
        "",
        "Media",
        "",
        "Media",
    ],
    pressKit: [
        "Press Kit",
        "Pressekit",
        "",
        "Pers kit",
        "",
        "Kit di stampa",
    ],
    services: [
        "Services",
        "Dienste",
        "",
        "Diensten",
        "",
        "Servizi",
    ],
    contestRules: [
        "Contest Rules",
        "Wettbewerbsregeln",
        "",
        "Wedstrijdreglement",
        "",
        "Regole del concorso",
    ],
    loggers: [
        "Loggers",
        "Logger",
        "",
        "Loggers",
        "",
        "Logger",
    ],
    developer: [
        "Developer",
        "Entwickler",
        "",
        "Ontwikkelaars",
        "",
        "Sviluppatori",
    ],
    getStarted: [
        "Get Started",
        "Einleitung",
        "",
        "Introductie",
        "",
        "Lavora con noi",
    ],
    faq: [
        "Frequent questions",
        "Häufige Fragen",
        "",
        "FAQ",
        "",
        "FAQ",
    ],

    // Teaser
    dailyBest: [
        "Daily best",
        "Tagesbeste",
        "",
        "Beste van de dag",
        "",
        "Migliore del giorno",
    ],
    latestUploads: [
        "Latest uploads",
        "Neu hochgeladen",
        "",
        "Nieuwste uploads",
        "",
        "Ultimo upload",
    ],
    flightStories: [
        "Flight Stories",
        "Fluggeschichten",
        "",
        "Vluchtverhalen",
        "",
        "Storie di volo",
    ],

    // Home Content
    magazine: [
        "Magazine",
        "Magazin",
        "",
        "Tijdschrift",
        "",
        "Notizie",
    ],
    magazineFeatures: [
        "WeGlide provides interactive flight data and maps to every story, video or article.",
        "WeGlide stellt interaktive Flugdaten und Karten zu jeder Geschichte, jedem Video oder Artikel.",
        "",
        "WeGlide biedt interactieve vluchtgegevens en kaarten voor elk verhaal, video of artikel.",
        "",
        "WeGlide fornisce dati di volo interattivi e mappe per ogni storia, video o articolo.",
    ],
    competitions: [
        "Competitions",
        "Wettbewerbe",
        "",
        "Wedstrijden",
        "",
        "Competizioni",
    ],
    competitionsFeatures: [
        "With our leading scoring algorithms we aim for fair competitions around the globe.",
        "Mit unseren führenden Wertungsalgorithmen streben wir gerechte Wettbewerbe rund um den Globus an.",
        "",
        "Met onze toonaangevende scoringsalgoritmen streven we naar eerlijke wedstrijden over de hele wereld. Ongeacht de regels.",
        "",
        "Con i nostri algoritmi di punteggio leader miriamo a competizioni eque in tutto il mondo.",
    ],
    team: [
        "Team",
        "Team",
        "",
        "Team",
        "",
        "Team",
    ],
    johannesDescription: [
        "Competition Pilot",
        "Wettbewerbspilot",
        "",
        "Wedstrijdvlieger",
        "",
        "Pilota da competizione",
    ],
    moritzDescription: [
        "Cross-Country Explorer",
        "Cross-Country Entdecker",
        "",
        "Overland verkenner",
        "",
        "Esploratore di nuovi mondi",
    ],
    samuelDescription: [
        "Outdoor Enthusiast",
        "Outdoor Abenteurer",
        "",
        "Outdoorliefhebber",
        "",
        "Appassionato di attività alla aperto",
    ],

    // Magazine Teaser
    readingTime: [
        "min. read",
        "Min. Lesezeit",
        "",
        "Min. Leestijd",
        "",
        "tempo di lettura",
    ],

    // Map layer
    mapLayer: [
        "Map layer",
        "Karte",
        "",
        "Kaart",
        "",
        "Carta geografica",
    ],
    comingSoon: [
        "Coming soon",
        "Kommt bald",
        "",
        "Komt binnenkort",
        "",
        "Prossimamente",
    ],
    transportation: [
        "Streets",
        "Straßen",
        "",
        "Transport",
        "",
        "Strade",
    ],
    landcover: [
        "Landcover",
        "Landbedeckung",
        "",
        "Landbedekking",
        "",
        "Copertura del suolo",
    ],
    administrative: [
        "Cities and Countries",
        "Städte und Länder",
        "",
        "Administratief",
        "",
        "Città e Paesi",
    ],
    pois: [
        "Points of interest",
        "Interessante Punkte",
        "",
        "Keerpunten",
        "",
        "Punti di interesse",
    ],
    weather: [
        "Weather",
        "Wetter",
        "",
        "Weer",
        "",
        "Tempo",
    ],
    satImage: [
        "Satellite image",
        "Satellitenbild",
        "",
        "Sattelietbeelden",
        "",
        "Immagini Satellitare",
    ],
    pfd: [
        "Predicted flight distance",
        "Vorhergesagte Flugdistanz",
        "",
        "Voorspelde vluchtafstand",
        "",
        "Distanza di volo prevista",
    ],
    rainRadar: [
        "Rain radar",
        "Regenradar",
        "",
        "Regenradar",
        "",
        "Radar pioggia",
    ],

    // Navigation
    start: [
        "Start",
        "Start",
        "",
        "Start",
        "",
        "Avvia",
    ],
    ranks: [
        "Ranks",
        "Wertung",
        "",
        "Plaats",
        "",
        "Rangk",
    ],
    upload: [
        "Upload",
        "Hochladen",
        "",
        "Uploaden",
        "",
        "Upload",
    ],
    task: [
        "Task",
        "Aufgabe",
        "",
        "Opdracht",
        "",
        "Obiettivi",
    ],
    profile: [
        "Profile",
        "Profil",
        "",
        "Profiel",
        "",
        "Profilo",
    ],
    logOut: [
        "Log out",
        "Ausloggen",
        "",
        "Log uit",
        "",
        "Disconnettiti",
    ],

    // Profile statistics
    joined: [
        "Joined WeGlide",
        "WeGlide Beigetreten",
        "",
        "Lid geworden van WeGlide",
        "",
        "Unito a WeGilde",
    ],
    stories: [
        "Stories",
        "Geschichten",
        "",
        "Verhalen",
        "",
        "Storie",
    ],
    airtime: [
        "Cumulative airtime",
        "Gesamte Flugzeit",
        "",
        "Totale vliegtijd",
        "",
        "Tempo totale di volo",
    ],
    cumulativeDistance: [
        "Cumulative distance",
        "Gesamte Distanz",
        "",
        "Totale afstand",
        "",
        "Distanza totale",
    ],
    avgSpeed: [
        "Average speed",
        "Durchschnittsgeschwindigkeit",
        "",
        "Gemiddelde snelheid",
        "",
        "Velocità media",
    ],
    avgGlideSpeed: [
        "Average glide speed",
        "Gleitgeschwindigkeit",
        "",
        "Gemiddelde glijsnelheid",
        "",
        "Velocità media di planata",
    ],
    avgGlideDetour: [
        "Average glide detour",
        "Durchschnittlicher Gleitumweg",
        "",
        "Gemiddelde glij omweg",
        "",
        "Deviazione media per planata",
    ],

    // Profile Settings
    profileSettings: [
        "Profile settings",
        "Profileinstellungen",
        "",
        "Profiel instellingen",
        "",
        "Impostazioni profilo",
    ],
    metric: [
        "Metric",
        "Metrisch",
        "",
        "Metrisch",
        "",
        "Metrico",
    ],
    imperial: [
        "Imperial",
        "Imperial",
        "",
        "Imperial",
        "",
        "Imperiale",
    ],
    integrateSkysight: [
        "Integrate SkySight weather data into WeGlide",
        "Integriere SkySight Wetter in WeGlide",
        "",
        "Integreer SkySight binnen WeGlide",
        "",
        "Integra i dati meteorologici SkySight in WeGlide",
    ],
    integrateTopmeteo: [
        "Integrate TopMeteo weather data into WeGlide",
        "Integriere TopMeteo Wetter in WeGlide",
        "",
        "Integreer TopMeteo binnen WeGlide",
        "",
        "Integra i dati meteorologici TopMeteo in WeGlide",
    ],

    // Profile
    settings: [
        "Settings",
        "Einstellungen",
        "",
        "Instellingen",
        "",
        "Impostazioni",
    ],
    flightsAsList: [
        "Flights as list",
        "Flüge als Liste",
        "",
        "Vluchten als lijst",
        "",
        "Voli come elenco",
    ],

    // Ranking
    ranking: [
        "Ranking",
        "Rangliste",
        "",
        "Rangschikking",
        "",
        "Classifica",
    ],
    contest: [
        "Contest",
        "Wettbewerb",
        "",
        "Wedstrijd",
        "",
        "Concorso",
    ],
    dmstDescription: [
        "German Championships",
        "Deutsche Meisterschaften",
        "",
        "Duitse kampioenschappen",
        "",
        "Campionato tedesco",
    ],
    plusDescription: [
        "WeGlide Distance Cup",
        "WeGlide Distanz Cup",
        "",
        "WeGlide afstandscup",
        "",
        "WeGlide Distance Cup",
    ],
    sprintDescription: [
        "WeGlide Speed Cup",
        "WeGlide Geschwindigkeits Cup",
        "",
        "WeGlide snelheidscup",
        "",
        "WeGlide Speed Cup",
    ],
    electricDescription: [
        "WeGlide FES Cup",
        "WeGlide FES Cup",
        "",
        "WeGlide FES-Cup",
        "",
        "WeGlide FES Cup",
    ],

    // Ranking config
    season: [
        "Season",
        "Saison",
        "",
        "Seizoen",
        "",
        "Season",
    ],
    gliderClass: [
        "Glider Class",
        "Flugzeugklasse",
        "",
        "Vliegtuigklasse",
        "",
        "Classe aereo",
    ],

    // Ranking table
    rank: [
        "Rank",
        "Rang",
        "",
        "Rang",
        "",
        "Rango",
    ],
    totalPoints: [
        "Total",
        "Gesamt",
        "",
        "Punten totaal",
        "",
        "Punti totali",
    ],

    // Story
    story: [
        "Story",
        "Geschichte",
        "",
        "Verhaal",
        "",
        "Storia",
    ],
    fullscreen: [
        "Fullscreen",
        "Vollbild",
        "",
        "Volledig scherm",
        "",
        "Schermo intero",
    ],
    beforeTakeoff: [
        "Before takeoff",
        "Vor dem Start",
        "",
        "Voor de starts",
        "",
        "Prima del decollo",
    ],
    afterLanding: [
        "After landing",
        "Nach der Landung",
        "",
        "Na de landing",
        "",
        "Dopo l'atterraggio",
    ],
    timeless: [
        "Timeless",
        "Zeitlos",
        "",
        "Tijdloos",
        "",
        "Senza tempo",
    ],
    until: [
        "until",
        "bis",
        "",
        "tot",
        "",
        "fino",
    ],
    addComment: [
        "Add comment",
        "Neuer Kommentar",
        "",
        "Nieuwe opmerking",
        "",
        "Aggiungi commento",
    ],
    addVideo: [
        "Add video",
        "Neues Video",
        "",
        "Niewe video",
        "",
        "Aggiungi video",
    ],
    imageDragText: [
        "Drag images here to upload or click to select",
        "Ziehe Bilder hierher zum Hochladen oder klicke zum Auswählen",
        "",
        "Sleep je foto hierheen om ze te uploaden of klik hier om ze te slecteren",
        "",
        "Trascina l'immagine qui per caricarla o clicca per selezionarla",
    ],
    imageDropText: [
        "Drop images to upload",
        "Lasse die Bilder los zum Hochladen",
        "",
        "Laat je foto's los om ze te uploaden",
        "",
        "Rilascia l'immagine per caricarla",
    ],
    writeComment: [
        "Write comment..",
        "Schreibe einen Kommentar..",
        "",
        "Plaats een opmerking...",
        "",
        "Scrivi un commento..",
    ],

    // Task
    tasks: [
        "Tasks",
        "Aufgaben",
        "",
        "Opdrachten",
        "",
        "Obiettivi",
    ],
    all: [
        "All",
        "Alle",
        "",
        "Alle",
        "",
        "Tutti",
    ],
    my: [
        "My",
        "Meine",
        "",
        "Mijn",
        "",
        "Mio",
    ],
    starred: [
        "Starred",
        "Favorisiert",
        "",
        "Favourieten",
        "",
        "Preferiti",
    ],
    myTasks: [
        "My tasks",
        "Meine Aufgaben",
        "",
        "Mijn opdrachten",
        "",
        "I miei obbiettivi",
    ],
    declare: [
        "declare",
        "deklarieren",
        "",
        "declareren",
        "",
        "dichiara",
    ],
    undeclare: [
        "undeclare",
        "entdeklarieren",
        "",
        "declaratie verwijderen",
        "",
        "non dichiarato",
    ],
    newTask: [
        "new task",
        "neue Aufgabe",
        "",
        "nieuwe opdracht",
        "",
        "nuovi obiettivi",
    ],
    noTaskDeclared: [
        "No declared task yet.",
        "Noch keine Aufgabe deklariert.",
        "",
        "Nog geen gedeclareerde opdracht.",
        "",
        "Ancora nessun obbiettivo dichiarato",
    ],
    noTasks: [
        "No tasks yet, plan a new one!",
        "Keine Aufgaben bis jetzt, plane eine!",
        "",
        "Nog geen opdracht, plan een nieuwe!",
        "",
        "Nessun obbiettivo, provvedi a selezionarne uno",
    ],
    position: [
        "Position",
        "Position",
        "",
        "Positie",
        "",
        "Posizione",
    ],
    startOnLeg: [
        "Start on leg",
        "Start auf Schenkel",
        "",
        "Begin op been",
        "",
        "Avvia",
    ],
    locked: [
        "Task is locked because it was once declared.",
        "Aufgabe ist gesperrt weil sie bereits deklariert wurde.",
        "",
        "Opdracht is vergrendeld omdat deze al is gedeclareerd.",
        "",
        "L'obbiettivo è bloccata perché è già stata dichiarata.",
    ],
    taskplaner: [
        "Taskplaner",
        "Aufgabenplaner",
        "",
        "Opdrachtplanner",
        "",
        "Pianificatore di attività",
    ],
    editTask: [
        "Edit task",
        "Aufgabe bearbeiten",
        "",
        "Opdracht aanpassen",
        "",
        "Modifica obbiettivo",
    ],
    taskName: [
        "Task name",
        "Aufgabenname",
        "",
        "Opdrachtnaam",
        "",
        "Nome obbiettivo",
    ],
    private: [
        "Only visible for me",
        "Nur sichtbar für mich",
        "",
        "Privé",
        "",
        "Visibile solo a te",
    ],
    turnpoints: [
        "Turnpoints",
        "Wendepunkte",
        "",
        "Keerpunten",
        "",
        "Punti di svolta",
    ],
    cupDragText: [
        "Drag a .cup file here to upload or click to select",
        "Ziehe eine CUP-Datei hierher zum Hochladen oder klicke zum Auswählen",
        "",
        "Sleep een .CUP-bestand hier naar toe om te uploaden of klik om te selecteren",
        "",
        "Trascina un file .cup qui o clicca per selezionarlo",
    ],
    cupDropText: [
        "Drop .cup file to upload",
        "Lasse die CUP-Datei los zum Hochladen",
        "",
        "Sleep een .CUP-bestand om deze te uploaden",
        "",
        "Rilascia il file .cup per caricarlo",
    ],
    taskSaved: [
        "Task saved",
        "Aufgabe gespeichert",
        "",
        "Opdracht bewaard",
        "",
        "Obbiettivo salvato",
    ],
    taskDeleted: [
        "Task deleted",
        "Aufgabe gelöscht",
        "",
        "Opdracht verwijderd",
        "",
        "Obbiettivo cancellato",
    ],
    turnpointHelp: [
        "Click on the map to add a turnpoint.",
        "Klicke auf die Karte für einen Wendepunkt.",
        "",
        "Klik op de kaart om een keerpunt toe te voegen.",
        "",
        "Clicca sulla mappa per aggiungere una meta",
    ],
    editHelp: [
        "Double click or drag to edit.",
        "Doppelt klicken oder ziehen zum Bearbeiten.",
        "",
        "Dubbel klik of verslepen om aan te passen.",
        "",
        "Fai doppio click o trascina per modificare.",
    ]
}

export function i18n(key: keyof typeof translations): string {
    if (!translations[key]) console.error("Translation not found for", key);
    if (translations[key][i18nStore.current] === "")
        return translations[key][0]; // english
    else
        return translations[key][i18nStore.current];
}
