import { i18nStore } from "@/shared/store"

// Main translation
export const translations = {
    /* Schema
    key: [
        "english",
        "german",
        "french",
        "dutch",
        "czech",
    ],
    */

    // Notification
    betaTitle: [
        "Prerelease",
        "Testversion",
        "",
        "Test versie",
        "Testovací verze",
    ],
    betaText: [
        "Please be aware that we might need to delete data or break some functionality.",
        "Bitte sei dir bewusst, dass wir eventuell Daten löschen müssen oder Fehler auftauchen.",
        "",
        "Ben je ervan bewust dat data verloren kan gaan en sommige functies nog niet goed werken.",
        "Prosím, buďte připraveni, že případně budeme muset data smazat nebo se může objevit chyba",
    ],
    waiting: [
        "Waiting",
        "Warten",
        "",
        "Wachtend",
        "čekej.",
    ],
    processing: [
        "Processing",
        "wird verarbeitet",
        "",
        "Wordt verwerkt",
        "Zpracovává se",
    ],
    attention: [
        "Attention",
        "Achtung",
        "Attention",
        "Attentie",
        "Pozor",
    ],
    success: [
        "Success",
        "Erfolg",
        "Avec succès",
        "Geslaagd",
        "Úspěch",
    ],
    errorAuthTitle: [
        "Session expired",
        "Sitzung abgelaufen",
        "",
        "Sessie vervallen",
        "Relace skončila",
    ],
    errorAuth: [
        "Please log in again",
        "Bitte logge dich erneut ein",
        "",
        "Log opniew in",
        "Prosím, přihlaš se znovu",
    ],
    errorServerTitle: [
        "Service unavailable",
        "Dienst nicht erreichbar",
        "",
        "Dienst niet beschikbaar",
        "Služba není k dispozici",
    ],
    errorServer: [
        "Please try again later or contact us",
        "Bitte versuche es später erneut oder kontaktiere uns",
        "",
        "Probeer het later nog eens",
        "Prosím zkus to později znovu nebo nás kontaktuj",
    ],
    errorForm: [
        "Please check your form inputs",
        "Bitte prüfe deine Formulareingaben",
        "",
        "Controleer het formulier",
        "Prosím zkontroluj si svá zadání ve formuláři",
    ],
    verified: [
        "Email verification complete, please log in.",
        "E-Mail wurde verifiziert, bitte einloggen.",
        "Votre adresse e-mail a été vérifiée, veuillez vous connecter s'il vous plait.",
        "Verificatie gelukt, log nu in.",
        "E-mailová adresa byla potvrzena, nyní se zkus přihlásit",
    ],
    notVerified: [
        "Please verify your Email first.",
        "Bitte verifiziere zuerst deine E-Mail.",
        "",
        "Verifieer je e-mailadres",
        "Prosím, ověřte nejdříve svoji emailovou adresu",
    ],
    resetComplete: [
        "Password reset complete, please log in.",
        "Passwort wurde zurückgesetzt, bitte einloggen.",
        "Votre mot de passe a été réinitialisé, veuillez vous connecter s'il vous plait.",
        "Wachtwoord hersteld, log nu in.",
        "Heslo bylo obnoveno, prosím přihlaš se",
    ],
    info: [
        "Info",
        "Info",
        "",
        "Informatie",
        "Informace",
    ],
    warning: [
        "Warning",
        "Warnung",
        "",
        "Waarschuwing",
        "Varování",
    ],
    error: [
        "Error",
        "Fehler",
        "",
        "Fout",
        "Chyba",
    ],
    analyzed: [
        "Analyzed",
        "Analyse",
        "",
        "Analyse",
        "Analýza",
    ],

    // Aircraft
    aircraft: [
        "Aircraft",
        "Flugzeug",
        "Avion",
        "Vliegtuig",
        "Letadlo",
    ],
    kind: [
        "Kind",
        "Art",
        "Sorte",
        "Soort",
        "Druh",
    ],
    glider: [
        "Glider",
        "Segelflugzeug",
        "",
        "Zweefvliegtuig",
        "Kluzák",
    ],
    fes: [
        "FES",
        "FES",
        "FES",
        "FES",
        "FES",
    ],
    engine: [
        "Engine",
        "Motor",
        "",
        "Motor",
        "Motor",
    ],
    paraglider: [
        "Paraglider",
        "Paragleiter",
        "",
        "Schermvlieger",
        "Paraglider",
    ],
    hangGlider: [
        "Hang Glider",
        "Drachen",
        "",
        "Deltavlieger",
        "Rogalo",
    ],
    ulGlider: [
        "UL Glider",
        "UL Gleiter",
        "",
        "UL Zweefvliegtuig",
        "UL Kluzák",
    ],
    family: [
        "Family",
        "Familie",
        "Famille",
        "Familie",
        "Rodina",
    ],
    manufacturer: [
        "Manufacturer",
        "Hersteller",
        "Fabricant",
        "Fabrikant",
        "Výrobce",
    ],
    seats: [
        "Seats",
        "Sitze",
        "Places",
        "Zitplaatsen",
        "Sedadel",
    ],
    class: [
        "Class",
        "Klasse",
        "Classe",
        "Klasse",
        "Třída",
    ],
    index: [
        "Index",
        "Index",
        "",
        "Index",
        "Index",
    ],
    igc: [
        "IGC",
        "IGC",
        "IGC",
        "IGC",
        "IGC",
    ],

    // Airport
    airport: [
        "Airport",
        "Flughafen",
        "Aéroport",
        "Vliegveld",
        "Letiště",
    ],
    airports: [
        "Airports",
        "Flughäfen",
        "",
        "Vliegvelds",
        "Letiště",
    ],
    radio: [
        "Radio",
        "Funk",
        "Radio",
        "Radio",
        "Rádio",
    ],
    frequency: [
        "Frequency",
        "Frequenz",
        "Fréquence",
        "Frequentie",
        "Frekvence",
    ],
    description: [
        "Description",
        "Beschreibung",
        "Description",
        "Omschrijving",
        "Popis",
    ],
    type: [
        "Type",
        "Typ",
        "Type",
        "Type",
        "Typ",
    ],
    category: [
        "Category",
        "Kategorie",
        "Catégorie",
        "Categorie",
        "Kategorie",
    ],
    location: [
        "Location",
        "Standort",
        "",
        "Lokatie",
        "Místo",
    ],
    timezone: [
        "Timezone",
        "Zeitzone",
        "",
        "Tijdzone",
        "Časové pásmo",
    ],
    region: [
        "Region",
        "Region",
        "Région",
        "Regio",
        "Region",
    ],
    elevation: [
        "Elevation",
        "Höhe",
        "Élévation",
        "Hoogte",
        "Výška",
    ],
    usage: [
        "Usage",
        "Nutzung",
        "",
        "Gebruik",
        "Využití	",
    ],
    coordinates: [
        "Coordinates",
        "Koordinaten",
        "Coordonnées",
        "Coördinaten",
        "Souřadnice",
    ],
    latitudeAbbrev: [
        "Lat.",
        "Lat.",
        "",
        "Lat.",
        "Lat",
    ],
    longitudeAbbrev: [
        "Lon.",
        "Lon.",
        "",
        "Lon.",
        "Lon",
    ],
    runway: [
        "Runway",
        "Piste",
        "",
        "Baan",
        "Dráha",
    ],
    length: [
        "Length",
        "Länge",
        "",
        "Lengte",
        "Délka",
    ],
    width: [
        "Width",
        "Breite",
        "",
        "Breedte",
        "Šířka",
    ],
    surface: [
        "Surface",
        "Oberfläche",
        "",
        "Soort",
        "Povrch",
    ],
    strength: [
        "Strength",
        "Stärke",
        "",
        "Sterkte",
        "Síla",
    ],
    glidingUsage: [
        "Gliding Usage",
        "Segelflugnutzung",
        "",
        "Zweefvliegterrein",
        "Plachtařské využití",
    ],
    reign: [
        "Reign",
        "Einflussgebiet",
        "",
        "Invloedgebied",
        "Oblast využití",
    ],
    launches: [
        "Gliding launches",
        "Segelflugstarts",
        "",
        "Zweefvliegstarts",
        "Start kluzáku",
    ],

    // Call to action
    reportFalseInformation: [
        "Report false information",
        "Melde falsche Informationen",
        "Signale fausses informations",
        "Meld verkeerde informatie",
        "Hláška chybné informace",
    ],
    logIn: [
        "Log in",
        "Einloggen",
        "Se connecter",
        "Inloggen",
        "Přihlásit se",
    ],
    signUp: [
        "Sign up",
        "Registrieren",
        "S'inscrire",
        "Registreren",
        "Registrovat se",
    ],
    forgotPassword: [
        "Forgot Password?",
        "Passwort vergessen?",
        "Mot de passe oublié?",
        "Wachtwoord vergeten?",
        "Zapomenuté heslo?",
    ],
    verifyEmail: [
        "Send verification link again",
        "Sende Verifizierungslink erneut",
        "",
        "Verstuur verificatie e-mail nogmaals",
        "Posílám nový potvrzovací odkaz",
    ],
    changePassword: [
        "Change Password",
        "Passwort ändern",
        "Changer mon mot de passe",
        "Wachtwoord veranderen",
        "Změnit heslo",
    ],
    resendVerification: [
        "Send verification link",
        "Verifizierungslink senden",
        "",
        "Verificatie e-mail versturen",
        "Poslat ověřovací odkaz",
    ],
    sendEmailAgain: [
        "Send email again",
        "E-Mail erneut senden",
        "Envoyer l'email à nouveau",
        "Email nogmaals versturen",
        "Poslat znovu e-mail",
    ],
    showStories: [
        "Show stories",
        "Zeige Geschichten",
        "",
        "Laat verhalen zien",
        "Zobrazit průběh",
    ],
    showAllArticles: [
        "Show all articles",
        "Zeige alle Artikel",
        "",
        "Laat alle artikelen zien",
        "Zobrazit všechny příspěvky",
    ],
    showLatest: [
        "Show latest",
        "Zeige Neueste",
        "",
        "Laatste bekijken",
        "Zobrazit nejnovější",
    ],
    showDaily: [
        "Show daily",
        "Zeige Tagesbeste",
        "",
        "Beste bekijken",
        "Zobrazit dnes nejlepší",
    ],
    cancel: [
        "Cancel",
        "Abbrechen",
        "Annuler",
        "Annuleer",
        "Zrušit",
    ],
    save: [
        "Save",
        "Speichern",
        "",
        "Opslaan",
        "Uložit",
    ],
    edit: [
        "Edit",
        "Bearbeiten",
        "",
        "Aanpassen",
        "Upravit",
    ],
    delete: [
        "Delete",
        "Löschen",
        "",
        "Verwijderen",
        "Smazat",
    ],
    show: [
        "show",
        "zeigen",
        "",
        "laten zien",
        "Zobrazit",
    ],

    // Flight
    flight: [
        "Flight",
        "Flug",
        "",
        "Vlucht",
        "Let",
    ],
    flights: [
        "Flights",
        "Flüge",
        "",
        "Vluchten",
        "Lety",
    ],
    allFlights: [
        "All flights",
        "Alle Flüge",
        "Tous les vols",
        "Alle vluchten",
        "Všechny lety",
    ],
    flightDeleted: [
        "Flight deleted",
        "Flug gelöscht",
        "",
        "Vlucht verwijderd",
        "Smazat let",
    ],
    flightSaved: [
        "Flight saved",
        "Flug gespeichert",
        "",
        "Vlucht opgeslagen",
        "Let uložen",
    ],
    flightDeleteConfirm: [
        "Do you really want to delete this flight?",
        "Möchtest du diesen Flug wirklich löschen?",
        "",
        "Wil je deze vlucht echt verwijderen?",
        "Chceš tento let opravdu smazat?",
    ],

    // User
    junior: [
        "Junior",
        "Junior*in",
        "",
        "Junior",
        "Junior",
    ],
    male: [
        "Male",
        "Männlich",
        "Masculin",
        "Man",
        "Muž",
    ],
    female: [
        "Female",
        "Weiblich",
        "Féminin",
        "Vrouw",
        "Žena",
    ],
    other: [
        "Other",
        "Divers",
        "Sexe neutre",
        "Anders",
        "Jiné",
    ],
    pilots: [
        "Pilots",
        "Pilot*innen",
        "",
        "Vlieger",
        "Pilot",
    ],

    // Meeting
    openFlight: [
        "Open flight",
        "Flug öffnen",
        "",
        "Vlucht openen",
        "Otevřít let",
    ],
    compare: [
        "Compare",
        "Vergleichen",
        "",
        "Vergelijken",
        "Porovnat",
    ],
    remove: [
        "Remove",
        "Entfernen",
        "",
        "Verwijderen",
        "Odstranit",
    ],

    // Task kind
    FR: [
        "Free",
        "Frei",
        "",
        "Vrije",
        "Volný",
    ],
    FR4: [
        "Free (DMSt)",
        "Frei (DMSt)",
        "",
        "Vrije (DMSt)",
        "Volný (DMSt)",
    ],
    GL: [
        "Goal",
        "Ziel",
        "",
        "Doel",
        "Cíl",
    ],
    TR: [
        "Triangle",
        "Dreieck",
        "",
        "Driehoek",
        "Trojúhelník",
    ],
    RT: [
        "Rectangle",
        "Viereck",
        "",
        "",
        "Čtyřúhelník",
    ],
    OR: [
        "Out and Return",
        "Zielrück",
        "",
        "Retour",
        "Návrat",
    ],
    closed: [
        "Closed",
        "Geschlossen",
        "",
        "Gesloten",
        "Uzavřený",
    ],
    open: [
        "Open",
        "Offen",
        "",
        "Open",
        "Otevřený",
    ],
    unnamed: [
        "Unnamed",
        "Unbenannt",
        "",
        "Zonder naam",
        "Nepojmenovaný",
    ],

    // Form fields
    email: [
        "Email",
        "E-Mail",
        "Adresse e-mail",
        "Email",
        "E-mail",
    ],
    password: [
        "Password",
        "Passwort",
        "Mot de passe",
        "Wachtwoord",
        "Heslo",
    ],
    name: [
        "Name",
        "Name",
        "Nom",
        "Naam",
        "Jméno",
    ],
    fullName: [
        "First and last name",
        "Vor- und Nachname",
        "Prénom et Nom",
        "Voor- en Achternaam",
        "Jméno a příjmení",
    ],
    birthdate: [
        "Date of birth",
        "Geburtsdatum",
        "Date de naissance",
        "Geboortedatum",
        "Datum narození",
    ],
    dateFormat: [
        "e.g. 1960-01-25 (YYYY-MM-DD)",
        "z.B. 1960-01-25 (JJJJ-MM-DD)",
        "",
        "b.v. 1960-01-25 (JJJJ-MM-DD)",
        "např. 1960-01-25 (JJJJ-MM-DD) ",
    ],
    club: [
        "Club",
        "Verein",
        "Club",
        "Club",
        "Klub",
    ],
    textConfirm: [
        "I have read and agree to the following documents:",
        "Ich habe die folgenden Dokumente gelesen und stimme zu:",
        "",
        "Ik heb de volgende documenten gelezen en ga akkoord:",
        "Přečetl jsem si následující dokumenty a souhlasím s nimi:",
    ],
    privacyPolicy: [
        "Privacy Policy",
        "Datenschutzerklärung",
        "",
        "Privacy Statement",
        "Prohlášení o ochraně osobních údajů",
    ],
    userAgreement: [
        "User Agreement",
        "Nutzungsbedingungen",
        "",
        "Voorwaarden",
        "Podmínky využití",
    ],
    subscribeNewsletter: [
        "Subscribe to our newsletter",
        "Abonniere unseren Newsletter",
        "Abonne-toi à notre newsletter",
        "Meld je aan voor de nieuwsbrief",
        "Chci odebírat zpravodaj",
    ],
    newPassword: [
        "New password",
        "Neues Passwort",
        "Nouveau mot de passe",
        "Nieuw wachtwoord",
        "Nové heslo",
    ],
    registration: [
        "Registration (optional)",
        "Registrierung (optional)",
        "",
        "Registreren (niet verpflicht)",
        "Registrace (opce)",
    ],
    coPilotName: [
        "Co-Pilot name",
        "Name Co-Pilot*in",
        "",
        "Tweede vlieger",
        "Jméno druhého pilota",
    ],
    coPilotDateOfBirth: [
        "Co-Pilot date of birth",
        "Co-Pilot Geburtsdatum",
        "",
        "Geboorte datum tweede vlieger",
        "Datum narození druhého pilota",
    ],
    competitionId: [
        "Competition ID (optional)",
        "Wettbewerbs-ID (optional)",
        "",
        "Wedstrijdnummer (niet verpflicht)",
        "Soutěžní znak (opce)",
    ],

    // Authentication
    joinThanks: [
        "Thank you for joining WeGlide!",
        "Wir freuen uns dich in der Community zu begrüßen!",
        "Merci d'avoir rejoint WeGlide!",
        "Bedankt voor je aanmelding bij WeGlide!",
        "Těší nás, že tě můžeme přivítat v naší komunitě!",
    ],
    urgeVerify: [
        "Please verify your email by clicking the link in the email you got.",
        "Bitte verifiziere deine E-Mail Adresse über den Link den wir dir zugesendet haben.",
        "Merci de vérifier ton adresse e-mail en cliquant sur le lien que nous t'avons envoyé ",
        "Verifieer je email adres door op de link te klikken die we je net hebben gestuurd.",
        "Prosíme o potvrzení tvé e-mailové adresy přes odkaz, který jsme ti zaslali. ",
    ],
    verifyInstructions: [
        "If not you got no email, please wait a minute and check your spam folder or contact us at",
        "Falls du keine E-Mail bekommen hast, warte eine Minute und prüfe deinen Spam-Ordner oder kontaktiere uns unter",
        "Si tu n'as pas recu de mail, attends une minute et regarde dans tes spams ou contactes nous",
        "Als je geen mail het gehad, wacht een paar minuten, controleer je spam folder of stuur ons een bericht.",
        "Pokud jsi žádný e-mail nedostal, počkej 1 minutu a případně prověř adresář Spam, nebo nás kontaktuj",
    ],
    joinCommunity: [
        "Join the community!",
        "Werde Teil der Community!",
        " 	Rejoins la communauté!",
        "Neem deel aan WeGlide!",
        "Připojuji se ke komunitě!",
    ],
    errorPrivacy: [
        "Please accept our privacy statements and terms.",
        "Bitte akzeptiere die Nutzungsbedingungen und Datenschutzerklärung.",
        "Merci d'accepter les conditions d'utilisation et la déclaration de confidentialité.",
        "Accepteer onze voorwaarden en het privacy statement.",
        "Prosíme o potvrzení uživatelských podmínek a prohlášení o ochraně osobních údajů",
    ],
    errorCaptcha: [
        "Please solve the captcha to verify you are human.",
        "Bitte löse das Captcha um zu zeigen dass du ein Mensch bist.",
        "",
        "Los de Captcha op om zeker te zijn dat je geen robot bent.",
        "Potvrď, že nejsi robot",
    ],
    verifying: [
        "Verifying Email",
        "E-Mail wird verifiziert",
        "Nous vérifions ton adresse e-mail",
        "Email wordt geverifieerd",
        "Ověřuji E-mail",
    ],
    urgeLogIn: [
        "Please log in afterwards",
        "Danach bitte einloggen",
        "Ensuite merci de vous connecter",
        "Daarna inloggen",
        "Poté se prosím přihlaš",
    ],
    requestVerification: [
        "Request new verification link",
        "Neuen Verifizierungslink anfordern",
        "",
        "Vraag nieuwe verificatie link aan",
        "Prosím o zaslání nového potvrzovacího odkazu",
    ],
    requestRecoverPassword: [
        "Request password recovery",
        "Passwort-Wiederherstellung anfordern",
        "Demander la récupération de mon mot de passe",
        "Wachtwoord herstel aanvragen",
        "Prosím o vytvoření nového hesla",
    ],
    instructionsEmailed: [
        "Email send, please follow the mailed instructions.",
        "E-Mail gesendet, bitte folge den dort beschriebenen Anweisungen",
        "Nous vous avons envoyé un mail avec les instructions à suivre pour récupérer votre mot de passe",
        "Email verstuurd",
        "E-mail byl odeslán, pokračuj dle postupu popsaném v e-mailu",
    ],
    recoverPassword: [
        "Recover password",
        "Passwort Wiederherstellen",
        "récupérer mon mot de passe",
        "Wachtwoord herstellen",
        "Vytvořit nové heslo",
    ],
    choosePassword: [
        "Choose new password",
        "Wähle ein neues Passwort",
        "Choisir un nouveau mot de passe",
        "Stel een nieuw wachtwoord in",
        "Vyberte nové heslo",
    ],
    resetInvalid: [
        "Password recovery link is no longer valid. Please request a new one.",
        "Link zur Passwort-Wiederherstellung ist abgelaufen. Bitte fordere einen neuen an.",
        "Le lien pour récupérer ton mot de passse est éxpiré. Merci d'en demander un nouveau.",
        "Wachtwoord herstel link is niet meer geldig. Vraag een nieuwe aan.",
        "Čas odkazu na vytvoření nového hesla vypršel. Prosím vyžádej si nový odkaz ",
    ],

    // Airspace
    airspace: [
        "Airspace",
        "Luftraum",
        "",
        "Luchtruim",
        "Vzdušný prostor",
    ],
    airspaces: [
        "Airspaces",
        "Lufträume",
        "",
        "Luchtruimen",
        "Vzdušné prostory",
    ],
    noAirspaceViolations: [
        "No airspaces crossed.",
        "Keine Lufträume durchflogen.",
        "",
        "Geen luchtruim schendingen.",
        "Nenarušeny žádné vzdušné prostory",
    ],

    // Page not found
    pageNotFound: [
        "Landing site not found",
        "Ort zum Landen nicht gefunden",
        "",
        "Pagina niet gevonden",
        "Stránka nenalezena",
    ],
    pickMeUp: [
        "Pick me up",
        "Bring mich zurück",
        "",
        "Breng me terug",
        "Zpět",
    ],

    // Filter
    filterPlaceholder: [
        "Search",
        "Suche",
        "",
        "Zoeken",
        "Hledat",
    ],

    // Flight detail
    flightDetail: [
        "Flight detail",
        "Flugdetails",
        "",
        "Vluchtdetails",
        "Podrobnosti letu",
    ],
    wingmen: [
        "Wingmen",
        "Gefährten",
        "",
        "Wingmen",
        "Partner",
    ],
    scoreProcessing: [
        "Scoring in process",
        "Punkte werden berechnet,",
        "",
        "Bezig met scoren",
        "Probíhá výpočet",
    ],
    pleaseReload: [
        "please reload this page.",
        "bitte lade die Seite neu.",
        "",
        "herlaad deze pagina.",
        "Načti stránku znovu",
    ],
    points: [
        "Points",
        "Punkte",
        "",
        "Punten",
        "Body",
    ],
    invalid: [
        "Invalid",
        "Ungültig",
        "",
        "Ongeldig",
        "Neplatné",
    ],
    invalidFlight: [
        "Flight claimed too late for this contest",
        "Flugmeldung zu spät für diese Wertung",
        "",
        "Vlucht te laat ingediend voor deze wedstrijd",
        "Nahlášení letu příliš pozdě na vyhodnocení soutěže",
    ],
    free: [
        "Free",
        "Frei",
        "",
        "Vrije",
        "Volný",
    ],
    speed: [
        "Speed",
        "Geschwindigkeit",
        "",
        "Snelheid",
        "Rychlost",
    ],
    triangle: [
        "Triangle",
        "Dreieck",
        "",
        "Driehoek",
        "Trojúhelník",
    ],
    rectangle: [
        "Rectangle",
        "Viereck",
        "",
        "Vierhoek",
        "Obdelník",
    ],
    declared: [
        "Declared",
        "Deklariert",
        "",
        "Gedeclareerd",
        "Deklarace",
    ],
    outReturn: [
        "Out and Return",
        "Zielrück",
        "",
        "Retour",
        "Návrat",
    ],
    convexHull: [
        "Convex Hull",
        "Konvexe Hülle",
        "",
        "Convex omhulsel",
        "Vypouklé pouzdro",
    ],
    teSpeed: [
        "EC Speed",
        "EK Geschwindigkeit",
        "",
        "TE Snelheid",
        "EC rychlost",
    ],
    teSpeedDescription: [
        "Energy Compensated Speed relative to task",
        "Energiekompensierte Geschwindigkeit relativ zur Aufgabe",
        "",
        "Endergie gecompenseerde snelheid i.r.t. opdracht",
        "",
    ],
    declaredTask: [
        "Declared Task",
        "Deklarierte Aufgabe",
        "",
        "Gedeclareerde opdracht",
        "Deklarovaná úloha",
    ],
    declaredTaskDescription: [
        "Task declared by pilot before flight",
        "Vom Piloten vor dem Flug deklarierte Aufgabe",
        "",
        "De opdracht die voor de vlucht is gedeclareed",
        "Úloha deklarovaná před vzletem",
    ],
    statistics: [
        "Statistics",
        "Statistiken",
        "",
        "Statistieken",
        "Statistika",
    ],
    general: [
        "General",
        "Allgemein",
        "",
        "Algemeen",
        "Všeobecné",
    ],
    distanceAbbrev: [
        "Dist.",
        "Dist.",
        "",
        "Afst.",
        "Vzdálenost",
    ],
    windAbbrev: [
        "Wind",
        "Wind",
        "",
        "Wind",
        "Vítr",
    ],
    electric: [
        "Electric",
        "Elektrisch",
        "",
        "Electrisch",
        "Elektrický",
    ],
    energyAbbrev: [
        "Energy",
        "Energie",
        "",
        "Energie",
        "Energie",
    ],
    total: [
        "Total",
        "Gesamt",
        "",
        "Totaal",
        "Celkem",
    ],
    thermaling: [
        "Thermaling",
        "Thermik",
        "",
        "Thermiek",
        "Kroužení",
    ],
    countAbbrev: [
        "Count",
        "Anzahl",
        "",
        "Aantal",
        "Počet",
    ],
    timeAbbrev: [
        "Time",
        "Zeit",
        "",
        "Tijd",
        "Čas",
    ],
    averageAbbrev: [
        "Avg.",
        "Schnitt",
        "",
        "Gem.",
        "Průměr",
    ],
    glide: [
        "Glide",
        "Gleiten",
        "",
        "Glijden",
        "Klouzavost",
    ],
    ratioAbbrev: [
        "Ratio",
        "Ratio",
        "",
        "Ratio",
        "Poměr",
    ],
    detourAbbrev: [
        "Detour",
        "Umweg",
        "",
        "Omweg",
        "Navíc",
    ],
    distance: [
        "Distance",
        "Distanz",
        "",
        "Afstand",
        "Vzdálenost",
    ],
    duration: [
        "Duration",
        "Dauer",
        "",
        "Duur",
        "Čas",
    ],
    takeoff: [
        "Takeoff",
        "Start",
        "",
        "Start",
        "Start",
    ],
    landing: [
        "Landing",
        "Landung",
        "",
        "Landing",
        "Přistání",
    ],
    status: [
        "Status",
        "Status",
        "",
        "Status",
        "Status",
    ],
    flightValid: [
        "flight valid",
        "Flug gültig",
        "",
        "Geldige vlucht",
        "Let je platný",
    ],
    flightInvalid: [
        "flight invalid",
        "Flug ungültig",
        "",
        "Ongeldige vlucht",
        "Let je neplatný",
    ],
    flightPending: [
        "flight pending",
        "Flug ausstehend",
        "",
        "Vlucht in afwachting",
        "Let čeká na zpracování",
    ],
    filePending: [
        "file pending",
        "Datei ausstehend",
        "",
        "Bestand in afwachting",
        "Soubor čeká na zpracování",
    ],
    fileHashValid: [
        "file hash valid",
        "Dateihash gültig",
        "",
        "Datahash geldig",
        "Soubor je platný",
    ],
    fileIgcValid: [
        "interim IGC valid",
        "Vorläufig IGC valide",
        "",
        "IGC data geldig",
        "IGC data jsou předběžně platná",
    ],
    fileInvalid: [
        "file interim invalid",
        "Datei vorläufig ungültig",
        "",
        "Data ongeldig",
        "Soubor je předběžně platný",
    ],
    comment: [
        "Comment (optional)",
        "Kommentar (optional)",
        "",
        "Opmerkingen (niet verplicht)",
        "Komentář (opce)",
    ],
    outstart: [
        "Outstart",
        "Außenstart",
        "",
        "Buitenstart",
        "Nenalezený start",
    ],
    outlanding: [
        "Outlanding",
        "Außenlandung",
        "",
        "Buitenlanding",
        "Přistání do terénu",
    ],
    fileValid: [
        "No remarks analyzing this flight.",
        "Keine Anmerkungen zur Analyse des Fluges.",
        "",
        "",
        "Žádné poznámky k analýze letu",
    ],
    loggerInformation: [
        "Logger information",
        "Logger Informationen",
        "",
        "Logger informatie",
        "Informace ze zapisovače letu",
    ],
    share: [
        "Share",
        "Teilen",
        "",
        "Delen",
        "Sdílet",
    ],
    embed: [
        "Embed",
        "Einbetten",
        "",
        "Integreren",
        "Vložit",
    ],
    showBarogram: [
        "Show barogram",
        "Barogram zeigen",
        "",
        "Laat barogram zien",
        "Zobrazit barozáznam",
    ],
    includeBBox: [
        "Current bounding box",
        "Aktueller Ausschnitt",
        "",
        "Actuele uitsnede",
        "Aktuální výběr",
    ],
    displayedFlights: [
        "Displayed flights",
        "Angezeigte Flüge",
        "",
        "Zichtbare vluchten",
        "Zobrazené lety",
    ],
    similarFlights: [
        "Similar flights",
        "Ähnliche Flüge",
        "",
        "Gelijke vluchten",
        "Podobné lety",
    ],

    // Flight list
    flightList: [
        "Flight list",
        "Flugliste",
        "",
        "Vluchtenlijst",
        "Seznam letů",
    ],
    flightOverviewSwitch: [
        "Map",
        "Karte",
        "",
        "Kaart",
        "Mapa",
    ],
    date: [
        "Date",
        "Datum",
        "",
        "Datum",
        "Datum",
    ],
    pilot: [
        "Pilot",
        "Pilot*in",
        "",
        "Vlieger",
        "Pilot",
    ],
    more: [
        "More",
        "Mehr",
        "",
        "Meer",
        "Více",
    ],
    noFlightsFilter: [
        "No flights with these filters.",
        "Keine Flüge mit diesen Filtern.",
        "",
        "Geen resultaten met deze filter",
        "Žádné lety dle parametrů vyhledávání",
    ],

    // Flight overview
    flightOverview: [
        "Flight overview",
        "Flugübersicht",
        "",
        "Overzicht",
        "Náhled letu",
    ],
    flightListSwitch: [
        "List",
        "Liste",
        "",
        "Lijst",
        "Seznam",
    ],

    // Upload/Edit
    uploadFlights: [
        "Upload flights",
        "Flüge hochladen",
        "",
        "Vlucht uploaden",
        "Nahrát lety",
    ],
    editFlight: [
        "Edit flight",
        "Flug bearbeiten",
        "",
        "VLucht aanpassen",
        "Upravit let",
    ],

    // Form edit flight
    scoringReset: [
        "Reset scoring windows",
        "Wertungsfenster zurücksetzen",
        "",
        "Scoringsgebied herstellen",
        "Obnovit vyhodnocení",
    ],
    scoringAdd: [
        "Add scoring window",
        "Neues Wertungsfenster",
        "",
        "Scoringsgebied toevoegen",
        "Přidat vyhodnocení",
    ],
    scoringStart: [
        "Scoring start",
        "Wertungsbeginn",
        "",
        "Begin van het scoren",
        "Začátek vyhodnocení",
    ],
    scoringEnd: [
        "Scoring end",
        "Wertungsende",
        "",
        "Eind van het scoren",
        "Konec vyhodnocení",
    ],
    registrationFormat: [
        "Only uppercase letters, numbers and '-' are allowed for registration.",
        "Nur Großbuchstaben, Ziffern und '-' sind die Registrierung erlaubt.",
        "",
        "Alleen hoofdletters, nummers en '-' zijn toegestaan voor registratie.",
        "V registraci jsou povoleny pouze velká písmena, čísla a '-' ",
    ],
    isNotRegistered: [
        "is not registered, no further authentication required.",
        "ist nicht registriert, keine Authentifizierung erforderlich.",
        "",
        "is niet geregistreerd, geen verdere authenticatie benodigd.",
        "Není registrován, není požadována autorizace",
    ],
    isRegistered: [
        "is registered, date of birth required as authentication.",
        "ist registriert, Geburtsdatum wird als Authentifizierung benötigt.",
        "",
        "is geregistreed, geboortedatum vereist voor authenticatie.",
        "Je registrován, pro autorizaci je nutné datum narození",
    ],
    competitionIdFormat: [
        "Only alphanumeric characters are allowed for competition id.",
        "Nur Alphanumerische Zeichen sind für die Wettbewerbs-ID erlaubt.",
        "",
        "Alleen alfanumerieke karakters zijn toegestaan als wedstrijdnummer.",
        "Na soutěžní znak jsou povoleny pouze písmena a čísla",
    ],
    scoringWindows: [
        "Scoring windows",
        "Wertungsfenster",
        "",
        "Scoringsgebied",
        "Vyhodnoceni",
    ],
    scoringTowingNotice: [
        "Please make sure that the scoring windows do not include towing.",
        "Bitte prüfe, dass die Wertungsfenster kein Schleppen beinhalten.",
        "",
        "Sleeptijd mag geen onderdeel zijn van het scoringsgebied.",
        "Ujistětě se, že ve vyhodnocení neobsahuje let v aerovleku",
    ],
    scoringiNotice: [
        "Airplane with electric propulsion selected. Please make sure time spans with running engine (yellow) are excluded from scoring.",
        "Flugzeug mit elektrischem Antrieb ausgewählt. Bitte prüfe, dass die Wertungsfenster keinen Motorlauf (gelb) beinhalten.",
        "",
        "Vliegtuig met electro motor geselecteerd, het scoringsgebied mag geen motorlooptijd bevatten.",
        "Vybrán kluzák s elektromotorem, ujistěte se, že ve vyhodnocení není část s během motoru (žlutá)",
    ],
    scoringEngineNotice: [
        "Airplane with engine selected. Please make sure time spans with running engine (yellow) are excluded from scoring.",
        "Flugzeug mit Motor ausgewählt. Bitte prüfe, dass die Wertungsfenster keinen Motorlauf (gelb) beinhalten.",
        "",
        "Vliegtuig met motor geselecteerd, het scoringgebied mag geen motorlooptijd bevatten.",
        "Vybrán kluzák s motorem, ujistěte se, že ve vyhodnocení není část letu s během motoru (žlutá)",
    ],
    errorTerms: [
        "Please agree to the terms.",
        "Bitte stimme den Bedingungen zu.",
        "",
        "Ga eerst akkoord met de voorwaarden.",
        "Prosíme o odsouhlasení podmínek",
    ],
    textConfirmUpload: [
        "I confirm that my scoring windows are chosen according to the rules, each active airspace crossed was cleared by ATC and I have read and accepted the following documents:",
        "Ich bestätige, dass ich die Wertungsfenster nach den Regeln gewählt habe, jeder durchflogene aktive Luftraum von ATC freigegeben wurde, und ich die folgenden Dokumente gelesen habe und ihnen zustimme:",
        "",
        "Ik bevestig dat mijn scoringsgebied(en) zijn geslecteerd volgens de regels, voor elk luchtruimbeperking had ik ATC-klaring en ik heb de volgende documenten gelezen en ga akkoord:",
        "Potvrzuji, že jsem zvolil vyhodnocení podle pravidel, průlet aktivních prostorů mi byl povolen četl jsem a akceptuji následující dokumenty:",
    ],

    // Form upload igc
    hello: [
        "Hello",
        "Hallo",
        "Bonjour",
        "Hallo",
        "Ahoj",
    ],
    shareFlights: [
        "share your flights!",
        "teile deine Flüge!",
        "",
        "deel je vluchten!",
        "Sdílej své lety",
    ],
    unauthorizedNotice: [
        "You are not logged in, please provide your date of birth and full name to upload if you have an account or",
        "Du bist nicht eingeloggt, bitte gib deinen vollen Namen sowie dein Geburtsdatum zum Hochladen an falls du einen Account hast oder",
        "",
        "Je bent niet ingelogd. Vul je volledige naam en geboortedatum in.",
        "Nejsi přihlášen, k nahrání letů napiš celé jméno a datum narození, pokud jsi již registrován",
    ],
    logInFirst: [
        "log in",
        "melde dich an",
        "",
        "log in",
        "Přihlásit",
    ],
    igcDragText: [
        "Drag .igc files here to upload or click to select",
        "Ziehe IGC-Dateien hierher zum Hochladen oder klicke zum Auswählen",
        "",
        "Sleep je .igc-bestanden hierheen om ze te uploaden of klik hier om ze te slecteren",
        "Přetáhni .igc soubor k nahrání nebo ho vyber ze seznamu",
    ],
    igcDropText: [
        "Drop .igc files to upload",
        "Lasse die IGC-Dateien los zum Hochladen",
        "",
        "Laat je .igc-bestenden los om ze te uploaden",
        "Přetáhni .igc soubor k nahrání",
    ],

    // Teaser
    currentLanguage: [
        "English",
        "Deutsch",
        "Français",
        "Nederlands",
        "Česky",
    ],
    welcome: [
        "Welcome",
        "Willkommen",
        "",
        "Welkom",
        "Vítejte",
    ],
    shareAdventures: [
        "Share your latest adventures.",
        "Teile deine neuesten Abenteuer.",
        "",
        "Deel je laatste avonturen",
        "Sdílej s námi o tvé nejnovější zážitky",
    ],
    uploadFlight: [
        "Upload flight",
        "Flug hochladen",
        "",
        "Vluchten uploaden",
        "Nahrát let",
    ],
    myProfile: [
        "My profile",
        "Mein Profil",
        "",
        "Mijn profiel",
        "Můj profil",
    ],
    encourage: [
        "Let's take off together and join the next-generation gliding platform.",
        "Lass uns zusammen abheben und genieße die Segelflugplattform der nächsten Generation.",
        "",
        "Laten we samen starten en sluit je aan bij het zweefplatform van de volgende generatie.",
        "Užij si novou platformu pro plachtění",
    ],
    fromByPilots: [
        "Built by Pilots for Pilots.",
        "Entworfen von Piloten für Pilot*innen.",
        "",
        "Gebouwd voor en door vliegers.",
        "Vytvořeno piloty pro piloty",
    ],

    // Partner
    partner: [
        "Partner",
        "Partner",
        "",
        "Partner",
        "Partner",
    ],
    sponsors: [
        "Funded by",
        "Gefördert durch",
        "",
        "Mede mogelijk gemaakt door",
        "Založeno ",
    ],
    logoLang: [
        "EN",
        "DE",
        "EN", // only en and de available
        "EN", // only en and de available
        "EN", // only en and de available
    ],

    // Footer
    contact: [
        "Contact",
        "Kontakt",
        "",
        "Contact",
        "Kontakt",
    ],
    philosophy: [
        "Philosophy",
        "Philosophie",
        "",
        "Filosofie",
        "Filozofie",
    ],
    imprint: [
        "Imprint",
        "Impressum",
        "",
        "Colofon",
        "Impresum",
    ],
    media: [
        "Media",
        "Medien",
        "",
        "Media",
        "Média",
    ],
    pressKit: [
        "Press Kit",
        "Pressekit",
        "",
        "Pers kit",
        "PR podklady",
    ],
    services: [
        "Services",
        "Dienste",
        "",
        "Diensten",
        "Služby",
    ],
    contestRules: [
        "Contest Rules",
        "Wettbewerbsregeln",
        "",
        "Wedstrijdreglement",
        "Soutěžní pravidla",
    ],
    loggers: [
        "Loggers",
        "Logger",
        "",
        "Loggers",
        "Zapisovače letu",
    ],
    developer: [
        "Developer",
        "Entwickler",
        "",
        "Ontwikkelaars",
        "Vývojář",
    ],
    getStarted: [
        "Get Started",
        "Einleitung",
        "",
        "Introductie",
        "Začínáme",
    ],
    faq: [
        "Frequent questions",
        "Häufige Fragen",
        "",
        "FAQ",
        "Často kladené otázky",
    ],

    // Teaser
    dailyBest: [
        "Daily best",
        "Tagesbeste",
        "",
        "Beste van de dag",
        "Dnes nejlepší",
    ],
    latestUploads: [
        "Latest uploads",
        "Neu hochgeladen",
        "",
        "Nieuwste uploads",
        "Poslední nahrané lety",
    ],
    flightStories: [
        "Flight Stories",
        "Fluggeschichten",
        "",
        "Vluchtverhalen",
        "Historie letu",
    ],

    // Home Content
    magazine: [
        "Magazine",
        "Magazin",
        "",
        "Tijdschrift",
        "Časopis",
    ],
    magazineFeatures: [
        "WeGlide provides interactive flight data and maps to every story, video or article.",
        "WeGlide stellt interaktive Flugdaten und Karten zu jeder Geschichte, jedem Video oder Artikel.",
        "",
        "WeGlide biedt interactieve vluchtgegevens en kaarten voor elk verhaal, video of artikel.",
        "Weglide poskytuje elektronická letová data, mapy, videa a články",
    ],
    competitions: [
        "Competitions",
        "Wettbewerbe",
        "",
        "Wedstrijden",
        "Soutěže",
    ],
    competitionsFeatures: [
        "With our leading scoring algorithms we aim for fair competitions around the globe.",
        "Mit unseren führenden Wertungsalgorithmen streben wir gerechte Wettbewerbe rund um den Globus an.",
        "",
        "Met onze toonaangevende scoringsalgoritmen streven we naar eerlijke wedstrijden over de hele wereld. Ongeacht de regels.",
        "Pomocí našich vyhodnocovacích výpočtů se snažíme dostat do soutěží probíhajících po celém světě. ",
    ],
    team: [
        "Team",
        "Team",
        "",
        "Team",
        "Tým",
    ],
    johannesDescription: [
        "Competition Pilot",
        "Wettbewerbspilot",
        "",
        "Wedstrijdvlieger",
        "Soutěžní pilot",
    ],
    moritzDescription: [
        "Cross-Country Explorer",
        "Cross-Country Entdecker",
        "",
        "Overland verkenner",
        "Vyhledávač po celém světě",
    ],
    samuelDescription: [
        "Outdoor Enthusiast",
        "Outdoor Abenteurer",
        "",
        "Outdoorliefhebber",
        "Outdorový dobrodruh",
    ],

    // Magazine Teaser
    readingTime: [
        "min. read",
        "Min. Lesezeit",
        "",
        "Min. Leestijd",
        "Min. čas čtení",
    ],

    // Map layer
    mapLayer: [
        "Map layer",
        "Karte",
        "",
        "Kaart",
        "Mapové vrstvy",
    ],
    comingSoon: [
        "Coming soon",
        "Kommt bald",
        "",
        "Komt binnenkort",
        "Přijde brzy",
    ],
    transportation: [
        "Streets",
        "Straßen",
        "",
        "Transport",
        "Silnice",
    ],
    landcover: [
        "Landcover",
        "Landbedeckung",
        "",
        "Landbedekking",
        "Zakrýt krajinu",
    ],
    administrative: [
        "Cities and Countries",
        "Städte und Länder",
        "",
        "Administratief",
        "Města a státy",
    ],
    pois: [
        "Points of interest",
        "Interessante Punkte",
        "",
        "Keerpunten",
        "Zájmové body",
    ],
    weather: [
        "Weather",
        "Wetter",
        "",
        "Weer",
        "Počasí",
    ],
    satImage: [
        "Satellite image",
        "Satellitenbild",
        "",
        "Sattelietbeelden",
        "Satelitní snímek",
    ],
    pfd: [
        "Predicted flight distance",
        "Vorhergesagte Flugdistanz",
        "",
        "Voorspelde vluchtafstand",
        "Předpovězená délka letu",
    ],
    rainRadar: [
        "Rain radar",
        "Regenradar",
        "",
        "Regenradar",
        "Srážkový radar",
    ],

    // Navigation
    start: [
        "Start",
        "Start",
        "",
        "Start",
        "Start",
    ],
    ranks: [
        "Ranks",
        "Wertung",
        "",
        "Plaats",
        "Pořadí",
    ],
    upload: [
        "Upload",
        "Hochladen",
        "",
        "Uploaden",
        "Nahrát",
    ],
    task: [
        "Task",
        "Aufgabe",
        "",
        "Opdracht",
        "Úloha",
    ],
    profile: [
        "Profile",
        "Profil",
        "",
        "Profiel",
        "Profil",
    ],
    logOut: [
        "Log out",
        "Ausloggen",
        "",
        "Log uit",
        "Odhlásit se",
    ],

    // Profile statistics
    joined: [
        "Joined WeGlide",
        "WeGlide Beigetreten",
        "",
        "Lid geworden van WeGlide",
        "Připoj se k WeGlide",
    ],
    stories: [
        "Stories",
        "Geschichten",
        "",
        "Verhalen",
        "Příběhy",
    ],
    airtime: [
        "Cumulative airtime",
        "Gesamte Flugzeit",
        "",
        "Totale vliegtijd",
        "Celková doba letu",
    ],
    cumulativeDistance: [
        "Cumulative distance",
        "Gesamte Distanz",
        "",
        "Totale afstand",
        "Celková vzdálenost",
    ],
    avgSpeed: [
        "Average speed",
        "Durchschnittsgeschwindigkeit",
        "",
        "Gemiddelde snelheid",
        "Průměrná rychlost",
    ],
    avgGlideSpeed: [
        "Average glide speed",
        "Gleitgeschwindigkeit",
        "",
        "Gemiddelde glijsnelheid",
        "Průměrná rychlost klouzání",
    ],
    avgGlideDetour: [
        "Average glide detour",
        "Durchschnittlicher Gleitumweg",
        "",
        "Gemiddelde glij omweg",
        "Průměrná vzdálenost mimo trať",
    ],

    // Profile Settings
    profileSettings: [
        "Profile settings",
        "Profileinstellungen",
        "",
        "Profiel instellingen",
        "Nastavení profilu",
    ],
    metric: [
        "Metric",
        "Metrisch",
        "",
        "Metrisch",
        "Metrické",
    ],
    imperial: [
        "Imperial",
        "Imperial",
        "",
        "Imperial",
        "Britské",
    ],
    integrateSkysight: [
        "Integrate SkySight weather data into WeGlide",
        "Integriere SkySight Wetter in WeGlide",
        "",
        "Integreer SkySight binnen WeGlide",
        "Propojení SkySight s WeGlide",
    ],
    integrateTopmeteo: [
        "Integrate TopMeteo weather data into WeGlide",
        "Integriere TopMeteo Wetter in WeGlide",
        "",
        "Integreer TopMeteo binnen WeGlide",
        "Propojení  TopMeteo s WeGlide",
    ],

    // Profile
    settings: [
        "Settings",
        "Einstellungen",
        "",
        "Instellingen",
        "Nastavení",
    ],
    flightsAsList: [
        "Flights as list",
        "Flüge als Liste",
        "",
        "Vluchten als lijst",
        "Lety ze seznamu",
    ],

    // Ranking
    ranking: [
        "Ranking",
        "Rangliste",
        "",
        "Rangschikking",
        "Umístění v žebříčku",
    ],
    contest: [
        "Contest",
        "Wettbewerb",
        "",
        "Wedstrijd",
        "Soutěž",
    ],
    dmstDescription: [
        "German Championships",
        "Deutsche Meisterschaften",
        "",
        "Duitse kampioenschappen",
        "Německý šampionát",
    ],
    plusDescription: [
        "WeGlide Distance Cup",
        "WeGlide Distanz Cup",
        "",
        "WeGlide afstandscup",
        "WeGlide Cup - vzdálenost",
    ],
    sprintDescription: [
        "WeGlide Speed Cup",
        "WeGlide Geschwindigkeits Cup",
        "",
        "WeGlide snelheidscup",
        "WeGlide Cup - rychlost",
    ],
    electricDescription: [
        "WeGlide electric cup",
        "WeGlide Elektrik Cup",
        "",
        "WeGlide electrisch cup",
        "WeGlide elektrický cup",
    ],

    // Ranking config
    season: [
        "Season",
        "Saison",
        "",
        "Seizoen",
        "Sezóna",
    ],
    gliderClass: [
        "Glider Class",
        "Flugzeugklasse",
        "",
        "Vliegtuigklasse",
        "Třída kluzáku",
    ],

    // Ranking table
    rank: [
        "Rank",
        "Rang",
        "",
        "Rang",
        "Pořadí",
    ],
    totalPoints: [
        "Total",
        "Gesamt",
        "",
        "Punten totaal",
        "Celkem",
    ],

    // Story
    story: [
        "Story",
        "Geschichte",
        "",
        "Verhaal",
        "Příběh",
    ],
    fullscreen: [
        "Fullscreen",
        "Vollbild",
        "",
        "Volledig scherm",
        "Na celou obrazovku",
    ],
    beforeTakeoff: [
        "Before takeoff",
        "Vor dem Start",
        "",
        "Voor de starts",
        "Před startem",
    ],
    afterLanding: [
        "After landing",
        "Nach der Landung",
        "",
        "Na de landing",
        "Po přistání",
    ],
    timeless: [
        "Timeless",
        "Zeitlos",
        "",
        "Tijdloos",
        "Nadčasový",
    ],
    until: [
        "until",
        "bis",
        "",
        "tot",
        "do",
    ],
    addComment: [
        "Add comment",
        "Neuer Kommentar",
        "",
        "Nieuwe opmerking",
        "Přidat komentář",
    ],
    addVideo: [
        "Add video",
        "Neues Video",
        "",
        "Niewe video",
        "Přidat video",
    ],
    imageDragText: [
        "Drag images here to upload or click to select",
        "Ziehe Bilder hierher zum Hochladen oder klicke zum Auswählen",
        "",
        "Sleep je foto hierheen om ze te uploaden of klik hier om ze te slecteren",
        "Sem přetáhni fotku k nahrání, nebo vyber ze seznamu",
    ],
    imageDropText: [
        "Drop images to upload",
        "Lasse die Bilder los zum Hochladen",
        "",
        "Laat je foto's los om ze te uploaden",
        "Přesuň sem obrázek k nahrání",
    ],
    writeComment: [
        "Write comment..",
        "Schreibe einen Kommentar..",
        "",
        "Plaats een opmerking...",
        "Napiš komentář",
    ],

    // Task
    tasks: [
        "Tasks",
        "Aufgaben",
        "",
        "Opdrachten",
        "Úloha",
    ],
    all: [
        "All",
        "Alle",
        "",
        "Alle",
        "Vše",
    ],
    my: [
        "My",
        "Meine",
        "",
        "Mijn",
        "Moje",
    ],
    starred: [
        "Starred",
        "Favorisiert",
        "",
        "Favourieten",
        "Oblíbené",
    ],
    myTasks: [
        "My tasks",
        "Meine Aufgaben",
        "",
        "Mijn opdrachten",
        "Moje úlohy",
    ],
    declare: [
        "declare",
        "deklarieren",
        "",
        "declareren",
        "Deklarovat",
    ],
    undeclare: [
        "undeclare",
        "entdeklarieren",
        "",
        "declaratie verwijderen",
        "oddeklarovat",
    ],
    newTask: [
        "new task",
        "neue Aufgabe",
        "",
        "nieuwe opdracht",
        "Nová úloha",
    ],
    noTaskDeclared: [
        "No declared task yet.",
        "Noch keine Aufgabe deklariert.",
        "",
        "Nog geen gedeclareerde opdracht.",
        "Dosud není deklarována žádná úloha",
    ],
    noTasks: [
        "No tasks yet, plan a new one!",
        "Keine Aufgaben bis jetzt, plane eine!",
        "",
        "Nog geen opdracht, plan een nieuwe!",
        "Dosud žádná úloha, naplánuj!",
    ],
    position: [
        "Position",
        "Position",
        "",
        "Positie",
        "Poloha",
    ],
    startOnLeg: [
        "Start on leg",
        "Start auf Schenkel",
        "",
        "Begin op been",
        "Start na rameni",
    ],
    locked: [
        "Task is locked because it was once declared.",
        "Aufgabe ist gesperrt weil sie bereits deklariert wurde.",
        "",
        "Opdracht is vergrendeld omdat deze al is gedeclareerd.",
        "Úloha je uzamčena, protože je již deklarována",
    ],
    taskplaner: [
        "Taskplaner",
        "Aufgabenplaner",
        "",
        "Opdrachtplanner",
        "Plánovač úloh",
    ],
    editTask: [
        "Edit task",
        "Aufgabe bearbeiten",
        "",
        "Opdracht aanpassen",
        "Upravit úlohu",
    ],
    taskName: [
        "Task name",
        "Aufgabenname",
        "",
        "Opdrachtnaam",
        "Název úlohy",
    ],
    private: [
        "Only visible for me",
        "Nur sichtbar für mich",
        "",
        "Privé",
        "Viditelné jen pro mě",
    ],
    turnpoints: [
        "Turnpoints",
        "Wendepunkte",
        "",
        "Keerpunten",
        "Otočné body",
    ],
    cupDragText: [
        "Drag a .cup file here to upload or click to select",
        "Ziehe eine CUP-Datei hierher zum Hochladen oder klicke zum Auswählen",
        "",
        "Sleep een .CUP-bestand hier naar toe om te uploaden of klik om te selecteren",
        "Přetáhni .cup soubor k nahrání, nebo vyber soubor",
    ],
    cupDropText: [
        "Drop .cup file to upload",
        "Lasse die CUP-Datei los zum Hochladen",
        "",
        "Sleep een .CUP-bestand om deze te uploaden",
        "Přetáhni .cup soubor k nahrání",
    ],
    taskSaved: [
        "Task saved",
        "Aufgabe gespeichert",
        "",
        "Opdracht bewaard",
        "Úloha uložena",
    ],
    taskDeleted: [
        "Task deleted",
        "Aufgabe gelöscht",
        "",
        "Opdracht verwijderd",
        "Úloha odstraněna",
    ],
    turnpointHelp: [
        "Click on the map to add a turnpoint.",
        "Klicke auf die Karte für einen Wendepunkt.",
        "",
        "Klik op de kaart om een keerpunt toe te voegen.",
        "Klikni na mapu pro přidání otočného bodu",
    ],
    editHelp: [
        "Double click or drag to edit.",
        "Doppelt klicken oder ziehen zum Bearbeiten.",
        "",
        "Dubbel klik of verslepen om aan te passen.",
        "Dvojitý klik nebo přetáhni pro úpravu",
    ]
}

export function i18n(key: keyof typeof translations): string {
    if (!translations[key]) console.error("Translation not found for", key);
    if (translations[key][i18nStore.current] === "")
        return translations[key][0]; // english
    else
        return translations[key][i18nStore.current];
}
