import { i18nStore } from "@/shared/store"

// Main translation
export const translations = {
    /* Schema
    key: [
        "english",
        "german",
        "french",
        "dutch",
        "czech",
        "italian",
    ],
    */

    // Notification
    betaTitle: [
        "Prerelease",
        "Testversion",
        "Version d'essai",
        "Test versie",
        "Testovací verze",
        "Prerelease",
    ],
    betaText: [
        "Please be aware that we might need to delete data or break some functionality.",
        "Bitte sei dir bewusst, dass wir eventuell Daten löschen müssen oder Fehler auftauchen.",
        "Merci de prendre en compte que nous serons éventuellement contraint d'effacer des données et que des erreurs peuvent survenir.",
        "Ben je ervan bewust dat data verloren kan gaan en sommige functies nog niet goed werken.",
        "Prosím, buďte připraveni, že případně budeme muset data smazat nebo se může objevit chyba",
        "Tieni presente che potrebbe essere necessario eliminare i dati o interrompere alcune funzionalità",
    ],
    waiting: [
        "Waiting",
        "Warten",
        "Attendre",
        "Wachtend",
        "čekej.",
        "In attesa",
    ],
    processing: [
        "Processing",
        "wird verarbeitet",
        "En traitement",
        "Wordt verwerkt",
        "Zpracovává se",
        "In elaborazione",
    ],
    attention: [
        "Attention",
        "Achtung",
        "Attention",
        "Attentie",
        "Pozor",
        "Attenzione",
    ],
    success: [
        "Success",
        "Erfolg",
        "Avec succès",
        "Geslaagd",
        "Úspěch",
        "Completato",
    ],
    errorAuthTitle: [
        "Session expired",
        "Sitzung abgelaufen",
        "Session expirée",
        "Sessie vervallen",
        "Relace skončila",
        "Sessione scaduta",
    ],
    errorAuth: [
        "Please log in again",
        "Bitte logge dich erneut ein",
        "Merci de te connecter à nouveau",
        "Log opniew in",
        "Prosím, přihlaš se znovu",
        "Effettua nuovamente l'accesso",
    ],
    errorServerTitle: [
        "Service unavailable",
        "Dienst nicht erreichbar",
        "Service non disponible",
        "Dienst niet beschikbaar",
        "Služba není k dispozici",
        "Server temporaneamente non disponibile",
    ],
    errorServer: [
        "Please try again later or contact us",
        "Bitte versuche es später erneut oder kontaktiere uns",
        "Merci de réessayer plus tard ou de nous contacter",
        "Probeer het later nog eens",
        "Prosím zkus to později znovu nebo nás kontaktuj",
        "Per favore, riprova più tardi o contattaci",
    ],
    errorForm: [
        "Please check your form inputs",
        "Bitte prüfe deine Formulareingaben",
        "Merci de vérifier les renseignements faits dans le formulaire",
        "Controleer het formulier",
        "Prosím zkontroluj si svá zadání ve formuláři",
        "Si prega di controllare gli input del modulo",
    ],
    verified: [
        "Email verification complete, please log in.",
        "E-Mail wurde verifiziert, bitte einloggen.",
        "Ton adresse e-mail a été vérifiée, merci de te connecter.",
        "Verificatie gelukt, log nu in.",
        "E-mailová adresa byla potvrzena, nyní se zkus přihlásit",
        "Verifica dell'email completata, esegui l'accesso",
    ],
    notVerified: [
        "Please verify your Email first.",
        "Bitte verifiziere zuerst deine E-Mail.",
        "Merci de d'abord vérifier ton adresse e-mail.",
        "Verifieer je e-mailadres",
        "Prosím, ověřte nejdříve svoji emailovou adresu",
        "Verifica prima la tua email.",
    ],
    resetComplete: [
        "Password reset complete, please log in.",
        "Passwort wurde zurückgesetzt, bitte einloggen.",
        "Ton mot de passe a été réinitialisé, merci de te connecter.",
        "Wachtwoord hersteld, log nu in.",
        "Heslo bylo obnoveno, prosím přihlaš se",
        "Reset della password completata, esegui l'accesso",
    ],
    info: [
        "Info",
        "Info",
        "Information",
        "Informatie",
        "Informace",
        "Informazioni",
    ],
    warning: [
        "Warning",
        "Warnung",
        "Avertissement",
        "Waarschuwing",
        "Varování",
        "Attenzione",
    ],
    error: [
        "Error",
        "Fehler",
        "Erreur",
        "Fout",
        "Chyba",
        "Errore",
    ],
    analyzed: [
        "Analyzed",
        "Analyse",
        "Analyse",
        "Analyse",
        "Analýza",
        "Analizzato",
    ],

    // Aircraft
    aircraft: [
        "Aircraft",
        "Flugzeug",
        "Avion",
        "Vliegtuig",
        "Letadlo",
        "Aereo",
    ],
    kind: [
        "Kind",
        "Art",
        "Sorte",
        "Soort",
        "Druh",
        "Tipo",
    ],
    glider: [
        "Glider",
        "Segelflugzeug",
        "Planeur",
        "Zweefvliegtuig",
        "Kluzák",
        "Aliante",
    ],
    fes: [
        "FES",
        "FES",
        "FES",
        "FES",
        "FES",
        "FES",
    ],
    engine: [
        "Engine",
        "Motor",
        "Moteur",
        "Motor",
        "Motor",
        "Motore",
    ],
    paraglider: [
        "Paraglider",
        "Paragleiter",
        "Parapente",
        "Schermvlieger",
        "Paraglider",
        "Parapendio",
    ],
    hangGlider: [
        "Hang Glider",
        "Drachen",
        "Deltaplane",
        "Deltavlieger",
        "Rogalo",
        "Deltaplano",
    ],
    ulGlider: [
        "UL Glider",
        "UL Gleiter",
        "Planeur ultra-léger motorisé",
        "UL Zweefvliegtuig",
        "UL Kluzák",
        "Aliante UL",
    ],
    family: [
        "Family",
        "Familie",
        "Famille",
        "Familie",
        "Rodina",
        "Famiglia",
    ],
    manufacturer: [
        "Manufacturer",
        "Hersteller",
        "Constructeur",
        "Fabrikant",
        "Výrobce",
        "Produttore",
    ],
    seats: [
        "Seats",
        "Sitze",
        "Places",
        "Zitplaatsen",
        "Sedadel",
        "Posti a sedere",
    ],
    class: [
        "Class",
        "Klasse",
        "Classe",
        "Klasse",
        "Třída",
        "Classe",
    ],
    index: [
        "Index",
        "Index",
        "Index",
        "Index",
        "Index",
        "Index",
    ],
    igc: [
        "IGC",
        "IGC",
        "IGC",
        "IGC",
        "IGC",
        "IGC",
    ],

    // Airport
    airport: [
        "Airport",
        "Flughafen",
        "Aéroport",
        "Vliegveld",
        "Letiště",
        "Aereoporto",
    ],
    airports: [
        "Airports",
        "Flughäfen",
        "Aéroports",
        "Vliegvelden",
        "Letiště",
        "Aereoporti",
    ],
    radio: [
        "Radio",
        "Funk",
        "Radio",
        "Radio",
        "Rádio",
        "Radio",
    ],
    frequency: [
        "Frequency",
        "Frequenz",
        "Fréquence",
        "Frequentie",
        "Frekvence",
        "Frequenza",
    ],
    description: [
        "Description",
        "Beschreibung",
        "Description",
        "Omschrijving",
        "Popis",
        "Descrizione",
    ],
    type: [
        "Type",
        "Typ",
        "Type",
        "Type",
        "Typ",
        "Tipo",
    ],
    category: [
        "Category",
        "Kategorie",
        "Catégorie",
        "Categorie",
        "Kategorie",
        "Categoria",
    ],
    location: [
        "Location",
        "Standort",
        "Localisation",
        "Lokatie",
        "Místo",
        "Posizione",
    ],
    timezone: [
        "Timezone",
        "Zeitzone",
        "Fuseau horaire",
        "Tijdzone",
        "Časové pásmo",
        "Fuso orario",
    ],
    region: [
        "Region",
        "Region",
        "Région",
        "Regio",
        "Region",
        "Regione",
    ],
    elevation: [
        "Elevation",
        "Höhe",
        "Élévation",
        "Hoogte",
        "Výška",
        "Elevazione",
    ],
    usage: [
        "Usage",
        "Nutzung",
        "Usage",
        "Gebruik",
        "Využití",
        "Utilizzo",
    ],
    coordinates: [
        "Coordinates",
        "Koordinaten",
        "Coordonnées",
        "Coördinaten",
        "Souřadnice",
        "Coordinate",
    ],
    latitudeAbbrev: [
        "Lat.",
        "Lat.",
        "Lat.",
        "Lat.",
        "Lat",
        "Lat.",
    ],
    longitudeAbbrev: [
        "Lon.",
        "Lon.",
        "Lon.",
        "Lon.",
        "Lon",
        "Lon.",
    ],
    runway: [
        "Runway",
        "Piste",
        "Piste",
        "Baan",
        "Dráha",
        "Pista di decollo",
    ],
    length: [
        "Length",
        "Länge",
        "Longueur",
        "Lengte",
        "Délka",
        "Lunghezza",
    ],
    width: [
        "Width",
        "Breite",
        "Largeur",
        "Breedte",
        "Šířka",
        "Altezza",
    ],
    surface: [
        "Surface",
        "Oberfläche",
        "Surface",
        "Soort",
        "Povrch",
        "Superficie",
    ],
    strength: [
        "Strength",
        "Stärke",
        "Force",
        "Sterkte",
        "Síla",
        "Potenza",
    ],
    glidingUsage: [
        "Gliding Usage",
        "Segelflugnutzung",
        "Usage d'un planeur",
        "Zweefvliegterrein",
        "Plachtařské využití",
        "Piano di volo",
    ],
    reign: [
        "Reign",
        "Einflussgebiet",
        "Zone d'influence",
        "Invloedgebied",
        "Oblast využití",
        "Area di influenza",
    ],
    launches: [
        "Gliding launches",
        "Segelflugstarts",
        "Décollages planeur",
        "Zweefvliegstarts",
        "Start kluzáku",
        "Decolli di alianti",
    ],

    // Call to action
    reportFalseInformation: [
        "Report false information",
        "Melde falsche Informationen",
        "Signale fausses informations",
        "Meld verkeerde informatie",
        "Hláška chybné informace",
        "Segnala informazioni false",
    ],
    logIn: [
        "Log in",
        "Einloggen",
        "Se connecter",
        "Inloggen",
        "Přihlásit se",
        "Accedi",
    ],
    signUp: [
        "Sign up",
        "Registrieren",
        "S'inscrire",
        "Registreren",
        "Registrovat se",
        "Registrati",
    ],
    forgotPassword: [
        "Forgot Password?",
        "Passwort vergessen?",
        "Mot de passe oublié?",
        "Wachtwoord vergeten?",
        "Zapomenuté heslo?",
        "Password dimenticata?",
    ],
    verifyEmail: [
        "Send verification link again",
        "Sende Verifizierungslink erneut",
        "Envoyer le lien de vérification à nouveau",
        "Verstuur verificatie e-mail nogmaals",
        "Posílám nový potvrzovací odkaz",
        "Invia di nuovo il link di verifica",
    ],
    changePassword: [
        "Change Password",
        "Passwort ändern",
        "Changer mon mot de passe",
        "Wachtwoord veranderen",
        "Změnit heslo",
        "Cambia password",
    ],
    resendVerification: [
        "Send verification link",
        "Verifizierungslink senden",
        "Envoyer le lien de vérification",
        "Verificatie e-mail versturen",
        "Poslat ověřovací odkaz",
        "Invia link di verifica",
    ],
    sendEmailAgain: [
        "Send email again",
        "E-Mail erneut senden",
        "Envoyer l'email à nouveau",
        "Email nogmaals versturen",
        "Poslat znovu e-mail",
        "Invia email di nuovo",
    ],
    showStories: [
        "Show stories",
        "Zeige Geschichten",
        "Voir les récits",
        "Bekijk meer verhalen",
        "Zobrazit průběh",
        "Mostra storie",
    ],
    showAllArticles: [
        "Show all articles",
        "Zeige alle Artikel",
        "Voir tous les articles",
        "Laat alle artikelen zien",
        "Zobrazit všechny příspěvky",
        "Mostra tutti gli articoli",
    ],
    showLatest: [
        "Show latest",
        "Zeige Neueste",
        "Voir nouveautés",
        "Bekijk meer vluchten",
        "Zobrazit nejnovější",
        "Mostra le ultime",
    ],
    showDaily: [
        "Show daily",
        "Zeige Tagesbeste",
        "Voir le meilleur vol du jour",
        "Alle vluchten van de dag",
        "Zobrazit dnes nejlepší",
        "Mostra articoli giornalieri",
    ],
    cancel: [
        "Cancel",
        "Abbrechen",
        "Annuler",
        "Annuleer",
        "Zrušit",
        "Cancella",
    ],
    save: [
        "Save",
        "Speichern",
        "Enregistrer",
        "Opslaan",
        "Uložit",
        "Salva",
    ],
    edit: [
        "Edit",
        "Bearbeiten",
        "Éditer",
        "Aanpassen",
        "Upravit",
        "Modifica",
    ],
    delete: [
        "Delete",
        "Löschen",
        "Supprimer",
        "Verwijderen",
        "Smazat",
        "Elimina",
    ],
    show: [
        "show",
        "zeigen",
        "montrer",
        "bekijken",
        "Zobrazit",
        "Mostra",
    ],

    // Flight
    flight: [
        "Flight",
        "Flug",
        "Vol",
        "Vlucht",
        "Let",
        "Volo",
    ],
    flights: [
        "Flights",
        "Flüge",
        "Vols",
        "Vluchten",
        "Lety",
        "Voli",
    ],
    allFlights: [
        "All flights",
        "Alle Flüge",
        "Tous les vols",
        "Alle vluchten",
        "Všechny lety",
        "Tutti i voli",
    ],
    flightDeleted: [
        "Flight deleted",
        "Flug gelöscht",
        "Vol supprimé",
        "Vlucht verwijderd",
        "Smazat let",
        "Volo Cancellato",
    ],
    flightSaved: [
        "Flight saved",
        "Flug gespeichert",
        "Vol enregistré",
        "Vlucht opgeslagen",
        "Let uložen",
        "Volo salvato",
    ],
    flightDeleteConfirm: [
        "Do you really want to delete this flight?",
        "Möchtest du diesen Flug wirklich löschen?",
        "Veux-tu vraiment supprimer ce vol?",
        "Wil je deze vlucht echt verwijderen?",
        "Chceš tento let opravdu smazat?",
        "Vuoi veramente cancellare questo volo?",
    ],

    // User
    junior: [
        "Junior",
        "Junior*in",
        "Junior",
        "Junior",
        "Junior",
        "Bambini",
    ],
    male: [
        "Male",
        "Männlich",
        "Masculin",
        "Man",
        "Muž",
        "Maschi",
    ],
    female: [
        "Female",
        "Weiblich",
        "Féminin",
        "Vrouw",
        "Žena",
        "Femmine",
    ],
    other: [
        "Other",
        "Divers",
        "Sexe neutre",
        "Anders",
        "Jiné",
        "Altro",
    ],
    pilots: [
        "Pilots",
        "Pilot*innen",
        "Pilotes",
        "Vliegers",
        "Pilot",
        "Piloti",
    ],

    // Meeting
    openFlight: [
        "Open flight",
        "Flug öffnen",
        "Ouvrir le vol",
        "Vlucht openen",
        "Otevřít let",
        "Apri il volo",
    ],
    compare: [
        "Compare",
        "Vergleichen",
        "Comparer",
        "Vergelijken",
        "Porovnat",
        "Confronta",
    ],
    remove: [
        "Remove",
        "Entfernen",
        "Enlever",
        "Verwijderen",
        "Odstranit",
        "Rimuovi",
    ],

    // Task kind
    FR: [
        "Free",
        "Frei",
        "Libre",
        "Vrije",
        "Volný",
        "Senza",
    ],
    FR4: [
        "Free (DMSt)",
        "Frei (DMSt)",
        "Libre (DMSt)",
        "Vrije (DMSt)",
        "Volný (DMSt)",
        "Senza (DMSt)"
    ],
    GL: [
        "Goal",
        "Ziel",
        "Objectif",
        "Doel",
        "Cíl",
        "Obiettivo",
    ],
    TR: [
        "Triangle",
        "Dreieck",
        "Triangle",
        "Driehoek",
        "Trojúhelník",
        "Triangolo",
    ],
    RT: [
        "Rectangle",
        "Viereck",
        "Quadrilatère",
        "Firkant",
        "Čtyřúhelník",
        "Rettangolo",
    ],
    OR: [
        "Out and Return",
        "Zielrück",
        "Aller-retour",
        "Retour",
        "Návrat",
        "Ritorno",
    ],
    closed: [
        "Closed",
        "Geschlossen",
        "Fermé",
        "Gesloten",
        "Uzavřený",
        "Chiuso",
    ],
    open: [
        "Open",
        "Offen",
        "Ouvert",
        "Open",
        "Otevřený",
        "Aperto",
    ],
    unnamed: [
        "Unnamed",
        "Unbenannt",
        "Anonyme",
        "Zonder naam",
        "Nepojmenovaný",
        "Senza nome",
    ],

    // Form fields
    email: [
        "Email",
        "E-Mail",
        "Adresse e-mail",
        "Email",
        "E-mail",
        "Email",
    ],
    password: [
        "Password",
        "Passwort",
        "Mot de passe",
        "Wachtwoord",
        "Heslo",
        "Password",
    ],
    name: [
        "Name",
        "Name",
        "Nom",
        "Naam",
        "Jméno",
        "Nome"
    ],
    fullName: [
        "First and last name",
        "Vor- und Nachname",
        "Prénom et Nom",
        "Voor- en Achternaam",
        "Jméno a příjmení",
        "Nome e Cognome",
    ],
    birthdate: [
        "Date of birth",
        "Geburtsdatum",
        "Date de naissance",
        "Geboortedatum",
        "Datum narození",
        "Data di nascita",
    ],
    dateFormat: [
        "e.g. 1960-01-25 (YYYY-MM-DD)",
        "z.B. 1960-01-25 (JJJJ-MM-DD)",
        "p.ex. 1960-01-25 (AAAA-MM-JJ)",
        "b.v. 1960-01-25 (JJJJ-MM-DD)",
        "např. 1960-01-25 (JJJJ-MM-DD)",
        "es. 1960-01-25 (YYYY-MM-DD)",
    ],
    club: [
        "Club",
        "Verein",
        "Club",
        "Club",
        "Klub",
        "Club",
    ],
    textConfirm: [
        "I have read and agree to the following documents:",
        "Ich habe die folgenden Dokumente gelesen und stimme zu:",
        "J'ai lu les documents et j'accepte:",
        "Ik heb de volgende documenten gelezen en ga akkoord:",
        "Přečetl jsem si následující dokumenty a souhlasím s nimi:",
        "Ho letto e accetto i seguenti documenti:",
    ],
    privacyPolicy: [
        "Privacy Policy",
        "Datenschutzerklärung",
        "Déclaration de confidentialité",
        "Privacy Statement",
        "Prohlášení o ochraně osobních údajů",
        "Politica sulla Privacy",
    ],
    userAgreement: [
        "User Agreement",
        "Nutzungsbedingungen",
        "Conditions d'utilisation",
        "Voorwaarden",
        "Podmínky využití",
        "Accordo per gli utenti",
    ],
    subscribeNewsletter: [
        "Subscribe to our newsletter",
        "Abonniere unseren Newsletter",
        "Abonne-toi à notre newsletter",
        "Meld je aan voor de nieuwsbrief",
        "Chci odebírat zpravodaj",
        "Iscriviti alla nostra Newsletter",
    ],
    newPassword: [
        "New password",
        "Neues Passwort",
        "Nouveau mot de passe",
        "Nieuw wachtwoord",
        "Nové heslo",
        "Nuova password",
    ],
    registration: [
        "Registration (optional)",
        "Registrierung (optional)",
        "S'inscrire (optionnel)",
        "Registreren (niet verpflicht)",
        "Registrace (opce)",
        "Registrazione (opzionale)",
    ],
    coPilotName: [
        "Co-Pilot name",
        "Name Co-Pilot*in",
        "Nom du co-pilote",
        "Tweede vlieger",
        "Jméno druhého pilota",
        "Nome copilota",
    ],
    coPilotDateOfBirth: [
        "Co-Pilot date of birth",
        "Co-Pilot Geburtsdatum",
        "Date de naissance du co-pilote",
        "Geboorte datum tweede vlieger",
        "Datum narození druhého pilota",
        "Data di nascita del copilota",
    ],
    competitionId: [
        "Competition ID (optional)",
        "Wettbewerbs-ID (optional)",
        "ID ou numéro de compétition (optionnel)",
        "Wedstrijdnummer (niet verpflicht)",
        "Soutěžní znak (opce)",
        "ID Concorenza (opzionale)",
    ],

    // Authentication
    joinThanks: [
        "Thank you for joining WeGlide!",
        "Wir freuen uns dich in der Community zu begrüßen!",
        "Merci d'avoir rejoint WeGlide!",
        "Bedankt voor je aanmelding bij WeGlide!",
        "Těší nás, že tě můžeme přivítat v naší komunitě!",
        "Grazie per esserti unito a WeGilde!",
    ],
    urgeVerify: [
        "Please verify your email by clicking the link in the email you got.",
        "Bitte verifiziere deine E-Mail Adresse über den Link den wir dir zugesendet haben.",
        "Merci de vérifier ton adresse e-mail en cliquant sur le lien que nous t'avons envoyé.",
        "Verifieer je email adres door op de link te klikken die we je net hebben gestuurd.",
        "Prosíme o potvrzení tvé e-mailové adresy přes odkaz, který jsme ti zaslali.",
        "Per favore verifica la tua email cliccando il link che ti è arrivato nella tua email",
    ],
    verifyInstructions: [
        "If not you got no email, please wait a minute and check your spam folder or contact us at",
        "Falls du keine E-Mail bekommen hast, warte eine Minute und prüfe deinen Spam-Ordner oder kontaktiere uns unter",
        "Si tu n'as pas reçu de mail, attends une minute et regarde dans tes spams ou contacte-nous sous",
        "Als je geen mail het gehad, wacht een paar minuten, controleer je spam folder of stuur ons een bericht.",
        "Pokud jsi žádný e-mail nedostal, počkej 1 minutu a případně prověř adresář Spam, nebo nás kontaktuj",
        "Se non hai ricevuto nessuna email, per favore aspetta un minuto e controlla la posta indesiderata o contattaci a",
    ],
    joinCommunity: [
        "Join the community!",
        "Werde Teil der Community!",
        "Rejoins la communauté!",
        "Neem deel aan WeGlide!",
        "Připojuji se ke komunitě!",
        "Unisciti alla community!",
    ],
    errorPrivacy: [
        "Please accept our privacy statements and terms.",
        "Bitte akzeptiere die Nutzungsbedingungen und Datenschutzerklärung.",
        "Merci d'accepter les conditions d'utilisation et la déclaration de confidentialité.",
        "Accepteer onze voorwaarden en het privacy statement.",
        "Prosíme o potvrzení uživatelských podmínek a prohlášení o ochraně osobních údajů",
        "Per favore accetta le nostre normative sulla privacy e i termini.",
    ],
    errorCaptcha: [
        "Please solve the captcha to verify you are human.",
        "Bitte löse das Captcha um zu zeigen dass du ein Mensch bist.",
        "Merci de résoudre le Captcha pour vérifier que tu n'est pas un robot.",
        "Los de Captcha op om zeker te zijn dat je geen robot bent.",
        "Potvrď, že nejsi robot",
        "Si prega di risolvere il captcha per verificare che non sei un robot",
    ],
    verifying: [
        "Verifying Email",
        "E-Mail wird verifiziert",
        "Nous vérifions ton adresse e-mail",
        "Email wordt geverifieerd",
        "Ověřuji E-mail",
        "Verificando l'email",
    ],
    urgeLogIn: [
        "Please log in afterwards",
        "Danach bitte einloggen",
        "Ensuite merci de te connecter",
        "Daarna inloggen",
        "Poté se prosím přihlaš",
        "Puoi effettuare il login",
    ],
    requestVerification: [
        "Request new verification link",
        "Neuen Verifizierungslink anfordern",
        "Demander un nouveau lien de vérification",
        "Vraag nieuwe verificatie link aan",
        "Prosím o zaslání nového potvrzovacího odkazu",
        "Richiedi un nuovo link di verifica",
    ],
    requestRecoverPassword: [
        "Request password recovery",
        "Passwort-Wiederherstellung anfordern",
        "Demander la récupération de mon mot de passe",
        "Wachtwoord herstel aanvragen",
        "Prosím o vytvoření nového hesla",
        "Richiedi password di recupero",
    ],
    instructionsEmailed: [
        "Email send, please follow the mailed instructions.",
        "E-Mail gesendet, bitte folge den dort beschriebenen Anweisungen",
        "Nous t'avons envoyé un mail avec les instructions à suivre pour récupérer ton mot de passe",
        "Email verstuurd",
        "E-mail byl odeslán, pokračuj dle postupu popsaném v e-mailu",
        "Email inviata, segui le istruzioni al suo interno",
    ],
    recoverPassword: [
        "Recover password",
        "Passwort Wiederherstellen",
        "Récupérer mon mot de passe",
        "Wachtwoord herstellen",
        "Vytvořit nové heslo",
        "Password di recupero",
    ],
    choosePassword: [
        "Choose new password",
        "Wähle ein neues Passwort",
        "Choisir un nouveau mot de passe",
        "Stel een nieuw wachtwoord in",
        "Vyberte nové heslo",
        "Scegli una nuova password",
    ],
    resetInvalid: [
        "Password recovery link is no longer valid. Please request a new one.",
        "Link zur Passwort-Wiederherstellung ist abgelaufen. Bitte fordere einen neuen an.",
        "Le lien pour récupérer ton mot de passe est expiré. Merci d'en demander un nouveau.",
        "Wachtwoord herstel link is niet meer geldig. Vraag een nieuwe aan.",
        "Čas odkazu na vytvoření nového hesla vypršel. Prosím vyžádej si nový odkaz ",
        "Il link per il recupero della password non è piu valido. Richiedine uno nuovo",
    ],

    // Airspace
    airspace: [
        "Airspace",
        "Luftraum",
        "Espace aérien",
        "Luchtruim",
        "Vzdušný prostor",
        "Spazio aereo",
    ],
    airspaces: [
        "Airspaces",
        "Lufträume",
        "Espaces aériens",
        "Luchtruim",
        "Vzdušné prostory",
        "Spazi aerei",
    ],
    noAirspaceViolations: [
        "No airspaces crossed.",
        "Keine Lufträume durchflogen.",
        "Pas d'espaces aériens traversés.",
        "Geen luchtruim schendingen.",
        "Nenarušeny žádné vzdušné prostory",
        "Nessuno spazio aereo incrociato",
    ],

    // Page not found
    pageNotFound: [
        "Landing site not found",
        "Ort zum Landen nicht gefunden",
        "L'endroit d'atterrissage n'a pas été trouvé.",
        "Pagina niet gevonden",
        "Stránka nenalezena",
        "Pagina non trovata",
    ],
    pickMeUp: [
        "Pick me up",
        "Bring mich zurück",
        "Ramène-moi en arrière",
        "Breng me terug",
        "Zpět",
        "Torna indietro",
    ],

    // Filter
    filterPlaceholder: [
        "Search",
        "Suche",
        "Recherche",
        "Zoeken",
        "Hledat",
        "Cerca",
    ],

    // Flight detail
    flightDetail: [
        "Flight detail",
        "Flugdetails",
        "Détails du vol",
        "Vluchtdetails",
        "Podrobnosti letu",
        "Dettagli del volo",
    ],
    wingmen: [
        "Wingmen",
        "Gefährten",
        "Partenaire d'équipe",
        "Ontmoetingen",
        "Partner",
        "Amici",
    ],
    scoreProcessing: [
        "Scoring in process",
        "Punkte werden berechnet,",
        "Calculation des points en cours,",
        "Bezig met scoren",
        "Probíhá výpočet",
        "Calcondo i punti",
    ],
    pleaseReload: [
        "please reload this page.",
        "bitte lade die Seite neu.",
        "merci de rafraîchir la page.",
        "herlaad deze pagina.",
        "Načti stránku znovu",
        "Per favore ricarica la pagina.",
    ],
    points: [
        "Points",
        "Punkte",
        "Points",
        "Punten",
        "Body",
        "Punti",
    ],
    invalid: [
        "Invalid",
        "Ungültig",
        "Invalide",
        "Ongeldig",
        "Neplatné",
        "Non valido",
    ],
    invalidFlight: [
        "Flight claimed too late for this contest",
        "Flugmeldung zu spät für diese Wertung",
        "Déclaration de vol trop tard pour ce classement",
        "Vlucht te laat ingediend voor deze wedstrijd",
        "Nahlášení letu příliš pozdě na vyhodnocení soutěže",
        "Il volo è stato richiesto troppo tardi per questo concorso",
    ],
    free: [
        "Free",
        "Frei",
        "Libre",
        "Vrije",
        "Volný",
        "Gratuito",
    ],
    speed: [
        "Speed",
        "Geschwindigkeit",
        "Vitesse",
        "Snelheid",
        "Rychlost",
        "Velocità",
    ],
    triangle: [
        "Triangle",
        "Dreieck",
        "",
        "Driehoek",
        "Trojúhelník",
        "Triangolo",
    ],
    rectangle: [
        "Rectangle",
        "Viereck",
        "Quadrilatère",
        "Vierhoek",
        "Obdelník",
        "Rettangolo",
    ],
    declared: [
        "Declared",
        "Deklariert",
        "Déclaré",
        "Gedeclareerd",
        "Deklarace",
        "Dichiarato",
    ],
    outReturn: [
        "Out and Return",
        "Zielrück",
        "Aller-retour",
        "Retour",
        "Návrat",
        "Ritorno",
    ],
    convexHull: [
        "Convex Hull",
        "Konvexe Hülle",
        "Enveloppe convexe",
        "Convex omhulsel",
        "Vypouklé pouzdro",
        "Scafo convesso",
    ],
    teSpeed: [
        "EC Speed",
        "EK Geschwindigkeit",
        "Vitesse CE",
        "TE Snelheid",
        "EC rychlost",
        "Velocità ER",
    ],
    teSpeedDescription: [
        "Energy Compensated Speed relative to task",
        "Energiekompensierte Geschwindigkeit relativ zur Aufgabe",
        "Vitesse compensée en énergie relative à l'épreuve",
        "Endergie gecompenseerde snelheid i.r.t. opdracht",
        "",
        "Velocità compensata dall'energia relativa al compito",
    ],
    declaredTask: [
        "Declared Task",
        "Deklarierte Aufgabe",
        "Performance déclarée",
        "Gedeclareerde opdracht",
        "Deklarovaná úloha",
        "Incarichi dichiarati",
    ],
    declaredTaskDescription: [
        "Task declared by pilot before flight",
        "Vom Piloten vor dem Flug deklarierte Aufgabe",
        "Performance/vol déclarée par le pilote avant le vol",
        "De opdracht die voor de vlucht is gedeclareed",
        "Úloha deklarovaná před vzletem",
        "Incarichi dichiarati dal pilota prima del volo",
    ],
    statistics: [
        "Statistics",
        "Statistiken",
        "Statistiques",
        "Statistieken",
        "Statistika",
        "Statistiche",
    ],
    general: [
        "General",
        "Allgemein",
        "Général",
        "Algemeen",
        "Všeobecné",
        "Generale",
    ],
    distanceAbbrev: [
        "Dist.",
        "Dist.",
        "Dist.",
        "Afst.",
        "Vzdálenost",
        "Dist.",
    ],
    windAbbrev: [
        "Wind",
        "Wind",
        "Vent",
        "Wind",
        "Vítr",
        "Vento",
    ],
    electric: [
        "Electric",
        "Elektrisch",
        "Électrique",
        "Electrisch",
        "Elektrický",
        "Elettricità",
    ],
    energyAbbrev: [
        "Energy",
        "Energie",
        "Énergie",
        "Energie",
        "Energie",
        "Energia",
    ],
    total: [
        "Total",
        "Gesamt",
        "Total",
        "Totaal",
        "Celkem",
        "Totale",
    ],
    thermaling: [
        "Thermaling",
        "Thermik",
        "Thermique",
        "Thermiek",
        "Kroužení",
        "Termico",
    ],
    countAbbrev: [
        "Count",
        "Anzahl",
        "Nombre",
        "Aantal",
        "Počet",
        "Numero",
    ],
    timeAbbrev: [
        "Time",
        "Zeit",
        "Temps",
        "Tijd",
        "Čas",
        "Tempo",
    ],
    averageAbbrev: [
        "Avg.",
        "Schnitt",
        "Vitesse moyenne",
        "Gem.",
        "Průměr",
        "Media",
    ],
    glide: [
        "Glide",
        "Gleiten",
        "Planer",
        "Glijden",
        "Klouzavost",
        "Planare",
    ],
    ratioAbbrev: [
        "Ratio",
        "Ratio",
        "Ratio",
        "Ratio",
        "Poměr",
        "Rapporto",
    ],
    detourAbbrev: [
        "Detour",
        "Umweg",
        "Détour",
        "Omweg",
        "Navíc",
        "Deviazione",
    ],
    distance: [
        "Distance",
        "Distanz",
        "Distance",
        "Afstand",
        "Vzdálenost",
        "Distanza",
    ],
    duration: [
        "Duration",
        "Dauer",
        "Durée",
        "Duur",
        "Čas",
        "Durata",
    ],
    takeoff: [
        "Takeoff",
        "Start",
        "Décollage",
        "Start",
        "Start",
        "Partenza",
    ],
    landing: [
        "Landing",
        "Landung",
        "Atterrissage",
        "Landing",
        "Přistání",
        "Atterraggio",
    ],
    status: [
        "Status",
        "Status",
        "Statut",
        "Status",
        "Status",
        "Stato",
    ],
    flightValid: [
        "flight valid",
        "Flug gültig",
        "Vol valide",
        "Geldige vlucht",
        "Let je platný",
        "Volo valido",
    ],
    flightInvalid: [
        "flight invalid",
        "Flug ungültig",
        "Vol invalide",
        "Ongeldige vlucht",
        "Let je neplatný",
        "Volo non valido",
    ],
    flightPending: [
        "flight pending",
        "Flug ausstehend",
        "Vol en attente",
        "Vlucht in afwachting",
        "Let čeká na zpracování",
        "Volo in attesa",
    ],
    filePending: [
        "file pending",
        "Datei ausstehend",
        "Fichier en attente",
        "Bestand in afwachting",
        "Soubor čeká na zpracování",
        "File in attesa",
    ],
    fileHashValid: [
        "file hash valid",
        "Dateihash gültig",
        "Hash du fichier valide",
        "Datahash geldig",
        "Soubor je platný",
        "Hash del file valido",
    ],
    fileIgcValid: [
        "interim IGC valid",
        "Vorläufig IGC valide",
        "Fichier IGC valide",
        "IGC data geldig",
        "IGC data jsou předběžně platná",
        "CIG provvisoria valida",
    ],
    fileInvalid: [
        "file interim invalid",
        "Datei vorläufig ungültig",
        "Fichier IGC invalide",
        "Data ongeldig",
        "Soubor je předběžně platný",
        "File non valido",
    ],
    comment: [
        "Comment",
        "Kommentar",
        "Commentaire",
        "Opmerkingen",
        "Komentář",
        "Commento",
    ],
    outstart: [
        "Outstart",
        "Außenstart",
        "Décollage extérieur",
        "Buitenstart",
        "Nenalezený start",
        "outstart",
    ],
    outlanding: [
        "Outlanding",
        "Außenlandung",
        "Atterrissage extérieur",
        "Buitenlanding",
        "Přistání do terénu",
        "outlanding",
    ],
    fileValid: [
        "No remarks analyzing this flight.",
        "Keine Anmerkungen zur Analyse des Fluges.",
        "Pas de remarques sur l'analyse du vol.",
        "",
        "Žádné poznámky k analýze letu",
        "Nessuna osservazione analizzando questo volo.",
    ],
    loggerInformation: [
        "Logger information",
        "Logger Informationen",
        "Informations de l'enregistreur",
        "Logger informatie",
        "Informace ze zapisovače letu",
        "Registro informazioni",
    ],
    share: [
        "Share",
        "Teilen",
        "Partager",
        "Delen",
        "Sdílet",
        "Condividi",
    ],
    embed: [
        "Embed",
        "Einbetten",
        "Intégrer",
        "Integreren",
        "Vložit",
        "Embed",
    ],
    showBarogram: [
        "Show barogram",
        "Barogram zeigen",
        "Montrer l'altitude enregistrée",
        "Laat barogram zien",
        "Zobrazit barozáznam",
        "Mostra barogramma",
    ],
    includeBBox: [
        "Current bounding box",
        "Aktueller Ausschnitt",
        "Extrait actuel",
        "Actuele uitsnede",
        "Aktuální výběr",
        "Riquadro di delimitazione",
    ],
    displayedFlights: [
        "Displayed flights",
        "Angezeigte Flüge",
        "Vols affichés",
        "Zichtbare vluchten",
        "Zobrazené lety",
        "Voli visualizzati",
    ],
    similarFlights: [
        "Similar flights",
        "Ähnliche Flüge",
        "Vols similaires",
        "Gelijke vluchten",
        "Podobné lety",
        "Voli simili",
    ],

    // Flight list
    flightList: [
        "Flight list",
        "Flugliste",
        "Liste des vols",
        "Vluchtenlijst",
        "Seznam letů",
        "Elenco dei voli",
    ],
    flightOverviewSwitch: [
        "Map",
        "Karte",
        "Carte",
        "Kaart",
        "Mapa",
        "Mappa",
    ],
    date: [
        "Date",
        "Datum",
        "Date",
        "Datum",
        "Datum",
        "Data",
    ],
    pilot: [
        "Pilot",
        "Pilot*in",
        "Pilote",
        "Individueel",
        "Pilot",
        "Pilota",
    ],
    more: [
        "More",
        "Mehr",
        "Plus",
        "Meer",
        "Více",
        "Altro",
    ],
    noFlightsFilter: [
        "No flights with these filters.",
        "Keine Flüge mit diesen Filtern.",
        "Pas de vols avec ce filtre.",
        "Geen resultaten met deze filter",
        "Žádné lety dle parametrů vyhledávání",
        "Nessun volo con questi filtri",
    ],

    // Flight overview
    flightOverview: [
        "Flight overview",
        "Flugübersicht",
        "Aperçu du vol",
        "Overzicht",
        "Náhled letu",
        "Panoramica volo",
    ],
    flightListSwitch: [
        "List",
        "Liste",
        "Liste",
        "Lijst",
        "Seznam",
        "Lista",
    ],

    // Upload/Edit
    uploadFlights: [
        "Upload flights",
        "Flüge hochladen",
        "Télécharger les vols",
        "Vlucht uploaden",
        "Nahrát lety",
        "Carica volo",
    ],
    editFlight: [
        "Edit flight",
        "Flug bearbeiten",
        "Éditer le vol",
        "VLucht aanpassen",
        "Upravit let",
        "Modifica volo",
    ],

    // Form edit flight
    scoringReset: [
        "Reset scoring windows",
        "Wertungsfenster zurücksetzen",
        "Réinitialiser fenêtre d'épreuve",
        "Scoringsgebied herstellen",
        "Obnovit vyhodnocení",
        "Resetta punteggi",
    ],
    scoringAdd: [
        "Add scoring window",
        "Neues Wertungsfenster",
        "Nouvelle fenêtre d'épreuve",
        "Scoringsgebied toevoegen",
        "Přidat vyhodnocení",
        "Aggiungi punteggio",
    ],
    scoringStart: [
        "Scoring start",
        "Wertungsbeginn",
        "Début de l'épreuve",
        "Begin van het scoren",
        "Začátek vyhodnocení",
        "Inizio punteggio",
    ],
    scoringEnd: [
        "Scoring end",
        "Wertungsende",
        "Fin de l'épreuve",
        "Eind van het scoren",
        "Konec vyhodnocení",
        "Fine punteggio",
    ],
    registrationFormat: [
        "Only uppercase letters, numbers and '-' are allowed for registration.",
        "Nur Großbuchstaben, Ziffern und '-' sind die Registrierung erlaubt.",
        "Seul les lettres majuscules, les chiffres et '-' sont permis pour l'inscription.",
        "Alleen hoofdletters, nummers en '-' zijn toegestaan voor registratie.",
        "V registraci jsou povoleny pouze velká písmena, čísla a '-' ",
        "Sono accettati solo lettere maiuscole, numeri e '-' per la registrazione. ",
    ],
    isNotRegistered: [
        "is not registered, no further authentication required.",
        "ist nicht registriert, keine Authentifizierung erforderlich.",
        "n'est pas enregistré, pas d'authentification nécessaire.",
        "is niet geregistreerd, geen verdere authenticatie benodigd.",
        "Není registrován, není požadována autorizace",
        "non è registrato, non è richiesta alcuna ulteriore autenticazione.",
    ],
    isRegistered: [
        "is registered, date of birth required as authentication.",
        "ist registriert, Geburtsdatum wird als Authentifizierung benötigt.",
        "est enregistré, date de naissance nécessaire pour l'authentification.",
        "is geregistreed, geboortedatum vereist voor authenticatie.",
        "Je registrován, pro autorizaci je nutné datum narození",
        "è registrato, la data di nascita è richiesta come autenticazione",
    ],
    competitionIdFormat: [
        "Only alphanumeric characters are allowed for competition id.",
        "Nur Alphanumerische Zeichen sind für die Wettbewerbs-ID erlaubt.",
        "Seul les caractères alphanumériques sont permis pour le numéro/ID de compétition.",
        "Alleen alfanumerieke karakters zijn toegestaan als wedstrijdnummer.",
        "Na soutěžní znak jsou povoleny pouze písmena a čísla",
        "Sono accettati sono caratteri alfanumerici per l' ID Concorenza",
    ],
    scoringWindows: [
        "Scoring windows",
        "Wertungsfenster",
        "Fenêtre pour le score",
        "Scoringsgebied",
        "Vyhodnoceni",
        "Finestra punteggi",
    ],
    scoringTowingNotice: [
        "Please make sure that the scoring windows do not include towing.",
        "Bitte prüfe, dass die Wertungsfenster kein Schleppen beinhalten.",
        "Merci de vérifier que la fenêtre d'épreuve ne contient pas de remorqué.",
        "Sleeptijd mag geen onderdeel zijn van het scoringsgebied.",
        "Ujistětě se, že ve vyhodnocení neobsahuje let v aerovleku",
        "Assicurati che la valutazione non includa un volo in traino aereo",
    ],
    scoringFesNotice: [
        "Airplane with electric propulsion selected. Please make sure time spans with running engine (yellow) are excluded from scoring.",
        "Flugzeug mit elektrischem Antrieb ausgewählt. Bitte prüfe, dass die Wertungsfenster keinen Motorlauf (gelb) beinhalten.",
        "Tu as choisi un avion avec moteur électrique. Merci de vérifier que les fenêtres d'épreuve ne contiennent pas de temps de moteur (jaune).",
        "Vliegtuig met electro motor geselecteerd, het scoringsgebied mag geen motorlooptijd bevatten.",
        "Vybrán kluzák s elektromotorem, ujistěte se, že ve vyhodnocení není část s během motoru (žlutá)",
        "Aereo con propulsione elettrica selezionato. Assicurati che i periodi di tempo con il motore in funzione (giallo) siano escusi dal punteggio",
    ],
    scoringEngineNotice: [
        "Airplane with engine selected. Please make sure time spans with running engine (yellow) are excluded from scoring.",
        "Flugzeug mit Motor ausgewählt. Bitte prüfe, dass die Wertungsfenster keinen Motorlauf (gelb) beinhalten.",
        "Tu as choisi un avion avec moteur. Merci de vérifier que les fenêtres d'épreuve ne contiennent pas de temps de moteur (jaune).",
        "Vliegtuig met motor geselecteerd, het scoringgebied mag geen motorlooptijd bevatten.",
        "Vybrán kluzák s motorem, ujistěte se, že ve vyhodnocení není část letu s během motoru (žlutá)",
        "Aereo con motore selezionato, Assicurati che i periodi di tempo con il motore in funzione (giallo) siano escusi dal punteggio",
    ],
    errorTerms: [
        "Please agree to the terms.",
        "Bitte stimme den Bedingungen zu.",
        "Merci d'accepter les conditions.",
        "Ga eerst akkoord met de voorwaarden.",
        "Prosíme o odsouhlasení podmínek",
        "Per favore accetta i termini.",
    ],
    textConfirmUpload: [
        "I confirm that my scoring windows are chosen according to the rules, each active airspace crossed was cleared by ATC and I have read and accepted the following documents:",
        "Ich bestätige, dass ich die Wertungsfenster nach den Regeln gewählt habe, jeder durchflogene aktive Luftraum von ATC freigegeben wurde, und ich die folgenden Dokumente gelesen habe und ihnen zustimme:",
        "Je confirme avoir choisi la fenêtre d'épreuve selon les règles, J'ai été autorisé par AIS à traverser les espaces aériens actifs et j'ai lu et approuvé les documents suivants:",
        "Ik bevestig dat mijn scoringsgebied(en) zijn geselecteerd volgens de regels, voor elk luchtruimbeperking had ik ATC-klaring en ik heb de volgende documenten gelezen en ga akkoord:",
        "Potvrzuji, že jsem zvolil vyhodnocení podle pravidel, průlet aktivních prostorů mi byl povolen četl jsem a akceptuji následující dokumenty:",
        "Confermo che le mie finestre di punteggio sono scelte in base alle regole che ogni spazio aereo attivo attraversato è stato cancellato dall'ATC e ho letto e accettato i seguenti documenti:",
    ],

    // Form upload igc
    hello: [
        "Hello",
        "Hallo",
        "Bonjour",
        "Hallo",
        "Ahoj",
        "Ciao",
    ],
    shareFlights: [
        "share your flights!",
        "teile deine Flüge!",
        "partage tes vols! ",
        "deel je vluchten!",
        "Sdílej své lety",
        "condividi i tuoi voli!",
    ],
    unauthorizedNotice: [
        "You are not logged in, please provide your date of birth and full name to upload if you have an account or",
        "Du bist nicht eingeloggt, bitte gib deinen vollen Namen sowie dein Geburtsdatum zum Hochladen an falls du einen Account hast oder",
        "Tu n'es pas connecté, merci d'entrer ton nom complet et ta date de naissance afin de pouvoir télécharger si tu as un compte ou",
        "Je bent niet ingelogd. Vul je volledige naam en geboortedatum in.",
        "Nejsi přihlášen, k nahrání letů napiš celé jméno a datum narození, pokud jsi již registrován",
        "Non hai effettuato l'accesso, per favore fornisci la tua data di nascita e il tuo nome completo se hai un account o",
    ],
    logInFirst: [
        "log in",
        "melde dich an",
        "inscris-toi",
        "log in",
        "Přihlásit",
        "log in",
    ],
    igcDragText: [
        "Drag .igc files here to upload or click to select",
        "Ziehe IGC-Dateien hierher zum Hochladen oder klicke zum Auswählen",
        "Tire tes fichiers IGC ici pour les télécharger ou clique pour les sélectionner",
        "Sleep je .igc-bestanden hierheen of klik hier om ze te selecteren",
        "Přetáhni .igc soubor k nahrání nebo ho vyber ze seznamu",
        "Trascina i file .igc qua per effettuare l'upload o clicca per selezionarli",
    ],
    igcDropText: [
        "Drop .igc files to upload",
        "Lasse die IGC-Dateien los zum Hochladen",
        "Lâche les fichiers IGC pour les télécharger",
        "Laat je .igc-bestanden los om ze te uploaden",
        "Přetáhni .igc soubor k nahrání",
        "Rilascia il file .igc",
    ],

    // Teaser
    currentLanguage: [
        "English",
        "Deutsch",
        "Français",
        "Nederlands",
        "Česky",
        "Italiano",
    ],
    welcome: [
        "Welcome",
        "Willkommen",
        "Bienvenue",
        "Welkom",
        "Vítejte",
        "Benvenuto",
    ],
    shareAdventures: [
        "Share your latest adventures.",
        "Teile deine neuesten Abenteuer.",
        "Partage tes aventures récentes.",
        "Deel je laatste avonturen!",
        "Sdílej s námi o tvé nejnovější zážitky",
        "Condividi le tue ultime avventure",
    ],
    uploadFlight: [
        "Upload flight",
        "Flug hochladen",
        "Télécharger le vol",
        "Vluchten uploaden",
        "Nahrát let",
        "Carica un volo",
    ],
    myProfile: [
        "My profile",
        "Mein Profil",
        "Mon profil",
        "Mijn profiel",
        "Můj profil",
        "Il mio profilo",
    ],
    encourage: [
        "Let's take off together and join the next-generation gliding platform.",
        "Lass uns zusammen abheben und genieße die Segelflugplattform der nächsten Generation.",
        "Viens décoller avec nous et profite de la nouvelle plate-forme autour du vol à voile de la nouvelle génération.",
        "Laten we samen starten en sluit je aan bij het zweefplatform van de volgende generatie.",
        "Užij si novou platformu pro plachtění",
        "Decolliamo insieme e unisciti alla nuova piattaforma di volo.",
    ],
    fromByPilots: [
        "Built by Pilots for Pilots.",
        "Entworfen von Piloten für Pilot*innen.",
        "Créé par des pilotes pour des pilotes.",
        "Gebouwd voor en door vliegers.",
        "Vytvořeno piloty pro piloty",
        "Costruito da piloti per piloti",
    ],

    // Partner
    partner: [
        "Partner",
        "Partner",
        "Partenaire",
        "Partner",
        "Partner",
        "Partner",
    ],
    sponsors: [
        "Funded by",
        "Gefördert durch",
        "Soutenu par",
        "Mede mogelijk gemaakt door",
        "Založeno",
        "Fondato da",
    ],
    logoLang: [
        "EN",
        "DE",
        "EN", // only en and de available
        "EN", // only en and de available
        "EN", // only en and de available
        "EN", // only en and de available
    ],

    // Footer
    contact: [
        "Contact",
        "Kontakt",
        "À propos",
        "Contact",
        "Kontakt",
        "Contatti",
    ],
    philosophy: [
        "Philosophy",
        "Philosophie",
        "Contact",
        "Filosofie",
        "Filozofie",
        "Filosofia",
    ],
    imprint: [
        "Imprint",
        "Impressum",
        "Mentions légales",
        "Colofon",
        "Impresum",
        "Impronta",
    ],
    media: [
        "Media",
        "Medien",
        "Médias",
        "Media",
        "Média",
        "Media",
    ],
    pressKit: [
        "Press Kit",
        "Pressekit",
        "Kit de presse",
        "Pers kit",
        "PR podklady",
        "Kit di stampa",
    ],
    services: [
        "Services",
        "Dienste",
        "Services",
        "Diensten",
        "Služby",
        "Servizi",
    ],
    contestRules: [
        "Contest Rules",
        "Wettbewerbsregeln",
        "Règles de compétition",
        "Wedstrijdreglement",
        "Soutěžní pravidla",
        "Regole del concorso",
    ],
    loggers: [
        "Loggers",
        "Logger",
        "Enregistreur",
        "Loggers",
        "Zapisovače letu",
        "Logger",
    ],
    developer: [
        "Developer",
        "Entwickler",
        "Développeur",
        "Ontwikkelaars",
        "Vývojář",
        "Sviluppatori",
    ],
    getStarted: [
        "Get Started",
        "Einleitung",
        "Introduction",
        "Introductie",
        "Uvedení",
        "Lavora con noi",
    ],
    faq: [
        "Frequent questions",
        "Häufige Fragen",
        "FAQ",
        "FAQ",
        "Často kladené otázky",
        "FAQ",
    ],

    // Teaser
    dailyBest: [
        "Daily best",
        "Tagesbeste",
        "Le meilleur du jour",
        "Dagelijkse score",
        "Dnes nejlepší",
        "Migliore del giorno",
    ],
    latestUploads: [
        "Latest uploads",
        "Neu hochgeladen",
        "Téléchargements récents",
        "Laatste vluchten",
        "Poslední nahrané lety",
        "Ultimo upload",
    ],
    flightStories: [
        "Flight Stories",
        "Fluggeschichten",
        "Récits de vols",
        "Verhalen",
        "Historie letu",
        "Storie di volo",
    ],

    // Home Content
    magazine: [
        "Magazine",
        "Magazin",
        "Magazine",
        "Artikelen",
        "Časopis",
        "Notizie",
    ],
    magazineFeatures: [
        "WeGlide provides interactive flight data and maps to every story, video or article.",
        "WeGlide stellt interaktive Flugdaten und Karten zu jeder Geschichte, jedem Video oder Artikel.",
        "WeGlide propose des données des vols et des cartes interactives pour chaque récit, chaque vidéo et chaque article.",
        "WeGlide biedt interactieve vluchtgegevens en kaarten voor elk verhaal, video of artikel.",
        "Weglide poskytuje elektronická letová data, mapy, videa a články",
        "WeGlide fornisce dati di volo interattivi e mappe per ogni storia, video o articolo.",
    ],
    competitions: [
        "Competitions",
        "Wettbewerbe",
        "Compétitions",
        "Wedstrijden",
        "Soutěže",
        "Competizioni",
    ],
    competitionsFeatures: [
        "With our leading scoring algorithms we aim for fair competitions around the globe.",
        "Mit unseren führenden Wertungsalgorithmen streben wir gerechte Wettbewerbe rund um den Globus an.",
        "Avec nos algorithmes leaders pour l'évaluation des vols, nous souhaitons réaliser des compétitions justes et équitables à travers le monde.",
        "Met onze toonaangevende scoringsalgoritmen streven we naar eerlijke wedstrijden over de hele wereld. Ongeacht de regels.",
        "Pomocí našich vyhodnocovacích výpočtů se snažíme dostat do soutěží probíhajících po celém světě.",
        "Con i nostri algoritmi di punteggio leader miriamo a competizioni eque in tutto il mondo.",
    ],
    team: [
        "Team",
        "Team",
        "Équipe",
        "Team",
        "Tým",
        "Team",
    ],
    johannesDescription: [
        "Competition Pilot",
        "Wettbewerbspilot",
        "Pilote de compétition",
        "Wedstrijdvlieger",
        "Soutěžní pilot",
        "Pilota da competizione",
    ],
    moritzDescription: [
        "Cross-Country Explorer",
        "Cross-Country Entdecker",
        "Pilote de découverte en vol libre",
        "Overland verkenner",
        "Vyhledávač po celém světě",
        "Esploratore di nuovi mondi",
    ],
    samuelDescription: [
        "Outdoor Enthusiast",
        "Outdoor Abenteurer",
        "Aventurier de plein air",
        "Outdoorliefhebber",
        "Outdorový dobrodruh",
        "Appassionato di attività alla aperto",
    ],

    // Magazine Teaser
    readingTime: [
        "min. read",
        "Min. Lesezeit",
        "Min. Temps de lecture",
        "Min. Leestijd",
        "Min. čas čtení",
        "tempo di lettura",
    ],

    // Map layer
    mapLayer: [
        "Map layer",
        "Karte",
        "Carte",
        "Kaart",
        "Mapové vrstvy",
        "Carta geografica",
    ],
    comingSoon: [
        "Coming soon",
        "Kommt bald",
        "Bientôt disponible",
        "Komt binnenkort",
        "Přijde brzy",
        "Prossimamente",
    ],
    transportation: [
        "Streets",
        "Straßen",
        "Rues",
        "Wegen",
        "Silnice",
        "Strade",
    ],
    landcover: [
        "Landcover",
        "Landbedeckung",
        "Couverture du sol",
        "Bodembedekking",
        "Zakrýt krajinu",
        "Copertura del suolo",
    ],
    administrative: [
        "Cities and Countries",
        "Städte und Länder",
        "Villes et pays",
        "Steden en Landen",
        "Města a státy",
        "Città e Paesi",
    ],
    pois: [
        "Points of interest",
        "Interessante Punkte",
        "Points intéressants",
        "Bezienswaardigheden",
        "Zájmové body",
        "Punti di interesse",
    ],
    weather: [
        "Weather",
        "Wetter",
        "Météo",
        "Weer",
        "Počasí",
        "Tempo",
    ],
    satImage: [
        "Satellite image",
        "Satellitenbild",
        "Image satellite",
        "Sattelietbeelden",
        "Satelitní snímek",
        "Immagini Satellitare",
    ],
    pfd: [
        "Predicted flight distance",
        "Vorhergesagte Flugdistanz",
        "Distance de vol prévue",
        "Voorspelde vluchtafstand",
        "Předpovězená délka letu",
        "Distanza di volo prevista",
    ],
    rainRadar: [
        "Rain radar",
        "Regenradar",
        "Radar de pluie",
        "Regenradar",
        "Srážkový radar",
        "Radar pioggia",
    ],
    thermalMaps: [
        "Thermal maps",
        "Thermikkarten",
        "Cartes thermiques",
        "Thermische kaarten",
        "Termální mapy",
        "Mappe termiche"
    ],

    // Navigation
    start: [
        "Start",
        "Start",
        "Départ",
        "Start",
        "Start",
        "Avvia",
    ],
    ranks: [
        "Ranks",
        "Wertung",
        "Classement",
        "Ranglijst",
        "Pořadí",
        "Rangk",
    ],
    upload: [
        "Upload",
        "Hochladen",
        "Télécharger",
        "Uploaden",
        "Nahrát",
        "Upload",
    ],
    task: [
        "Task",
        "Aufgabe",
        "Performance",
        "Opdracht",
        "Úloha",
        "Obiettivi",
    ],
    profile: [
        "Profile",
        "Profil",
        "Profil",
        "Profiel",
        "Profil",
        "Profilo",
    ],
    logOut: [
        "Log out",
        "Ausloggen",
        "Se déconnecter",
        "Log uit",
        "Odhlásit se",
        "Disconnettiti",
    ],

    // Profile statistics
    joined: [
        "Joined WeGlide",
        "WeGlide Beigetreten",
        "Tu as rejoins WeGlide",
        "Lid sinds",
        "Připoj se k WeGlide",
        "Unito a WeGilde",
    ],
    stories: [
        "Stories",
        "Geschichten",
        "Récits",
        "Verhalen",
        "Příběhy",
        "Storie",
    ],
    airtime: [
        "Cumulative airtime",
        "Gesamte Flugzeit",
        "Durée de vol totale",
        "Vliegtijd",
        "Celková doba letu",
        "Tempo totale di volo",
    ],
    cumulativeDistance: [
        "Cumulative distance",
        "Gesamte Distanz",
        "Distance de vol totale",
        "Afstand",
        "Celková vzdálenost",
        "Distanza totale",
    ],
    avgSpeed: [
        "Average speed",
        "Durchschnittsgeschwindigkeit",
        "Vitesse moyenne",
        "Snelheid",
        "Průměrná rychlost",
        "Velocità media",
    ],
    avgGlideSpeed: [
        "Average glide speed",
        "Gleitgeschwindigkeit",
        "Vitesse",
        "Steeksnelheid",
        "Průměrná rychlost klouzání",
        "Velocità media di planata",
    ],
    avgGlideDetour: [
        "Average glide detour",
        "Durchschnittlicher Gleitumweg",
        "Moyenne distance de détour planée",
        "Omvliegfactor",
        "Průměrná vzdálenost mimo trať",
        "Deviazione media per planata",
    ],

    // Profile Settings
    profileSettings: [
        "Profile settings",
        "Profileinstellungen",
        "Réglages de mon profil",
        "Profiel instellingen",
        "Nastavení profilu",
        "Impostazioni profilo",
    ],
    metric: [
        "Metric",
        "Metrisch",
        "Métrique",
        "Metrisch",
        "Metrické",
        "Metrico",
    ],
    imperial: [
        "Imperial",
        "Imperial",
        "Impérial",
        "Imperiaal",
        "Britské",
        "Imperiale",
    ],
    integrateSkysight: [
        "Integrate SkySight weather data into WeGlide",
        "Integriere SkySight Wetter in WeGlide",
        "Intègre la météo de SkySight sur WeGlide",
        "SkySight integratie",
        "Propojení SkySight s WeGlide",
        "Integra i dati meteorologici SkySight in WeGlide",
    ],
    integrateTopmeteo: [
        "Integrate TopMeteo weather data into WeGlide",
        "Integriere TopMeteo Wetter in WeGlide",
        "Intègre la météo de TopMeteo sur WeGlide",
        "TopMeteo integratie",
        "Propojení  TopMeteo s WeGlide",
        "Integra i dati meteorologici TopMeteo in WeGlide",
    ],

    // Profile
    settings: [
        "Settings",
        "Einstellungen",
        "Réglages",
        "Instellingen",
        "Nastavení",
        "Impostazioni",
    ],
    flightsAsList: [
        "Flights as list",
        "Flüge als Liste",
        "Vols sous forme de liste",
        "Vluchtenlijst",
        "Lety ze seznamu",
        "Voli come elenco",
    ],

    // Ranking
    ranking: [
        "Ranking",
        "Rangliste",
        "Liste de classement",
        "Ranglijst",
        "Umístění v žebříčku",
        "Classifica",
    ],
    contest: [
        "Contest",
        "Wettbewerb",
        "Compétition",
        "Wedstrijd",
        "Soutěž",
        "Concorso",
    ],
    dmstDescription: [
        "German Championships",
        "Deutsche Meisterschaften",
        "Championnat allemand",
        "Duitse kampioenschappen",
        "Německý šampionát",
        "Campionato tedesco",
    ],
    freeDescription: [
        "WeGlide Distance Cup",
        "WeGlide Distanz Cup",
        "Compétition de distance WeGlide",
        "WeGlide afstandscup",
        "WeGlide Cup - vzdálenost",
        "WeGlide Distance Cup",
    ],
    sprintDescription: [
        "WeGlide Speed Cup",
        "WeGlide Geschwindigkeits Cup",
        "Compétition de vitesse WeGlide",
        "WeGlide snelheidscup",
        "WeGlide Cup - rychlost",
        "WeGlide Speed Cup",
    ],
    electricDescription: [
        "WeGlide electric cup",
        "WeGlide Elektrik Cup",
        "Compétition électrique WeGlide",
        "WeGlide electrisch cup",
        "WeGlide elektrický cup",
        "WeGlide Electric Cup",
    ],

    // Ranking config
    season: [
        "Season",
        "Saison",
        "Saison",
        "Seizoen",
        "Sezóna",
        "Season",
    ],
    gliderClass: [
        "Glider Class",
        "Flugzeugklasse",
        "Classe planeur",
        "Klasse",
        "Třída kluzáku",
        "Classe aereo",
    ],

    // Ranking table
    rank: [
        "Rank",
        "Rang",
        "Rank",
        "Plaats",
        "Pořadí",
        "Rango",
    ],
    totalPoints: [
        "Total",
        "Gesamt",
        "Récit",
        "Punten totaal",
        "Celkem",
        "Punti totali",
    ],

    // Story
    story: [
        "Story",
        "Geschichte",
        "Récit",
        "Verhaal",
        "Příběh",
        "Storia",
    ],
    fullscreen: [
        "Fullscreen",
        "Vollbild",
        "Plein écran",
        "Volledig scherm",
        "Na celou obrazovku",
        "Schermo intero",
    ],
    beforeTakeoff: [
        "Before takeoff",
        "Vor dem Start",
        "Avant le décollage",
        "Voor de starts",
        "Před startem",
        "Prima del decollo",
    ],
    afterLanding: [
        "After landing",
        "Nach der Landung",
        "Après l'atterrissage",
        "Na de landing",
        "Po přistání",
        "Dopo l'atterraggio",
    ],
    timeless: [
        "Timeless",
        "Zeitlos",
        "Intemporel",
        "Tijdloos",
        "Nadčasový",
        "Senza tempo",
    ],
    until: [
        "until",
        "bis",
        "Jusqu'à",
        "tot",
        "do",
        "fino",
    ],
    addComment: [
        "Add comment",
        "Neuer Kommentar",
        "Nouveau commentaire",
        "Nieuwe opmerking",
        "Přidat komentář",
        "Aggiungi commento",
    ],
    addVideo: [
        "Add video",
        "Neues Video",
        "Nouvelle vidéo",
        "Niewe video",
        "Přidat video",
        "Aggiungi video",
    ],
    imageDragText: [
        "Drag images here to upload or click to select",
        "Ziehe Bilder hierher zum Hochladen oder klicke zum Auswählen",
        "Tire tes photos ici pour les télécharger ou clique sur sélectionner",
        "Sleep je foto's hierheen of klik hier om ze te selecteren",
        "Sem přetáhni fotku k nahrání, nebo vyber ze seznamu",
        "Trascina l'immagine qui per caricarla o clicca per selezionarla",
    ],
    imageDropText: [
        "Drop images to upload",
        "Lasse die Bilder los zum Hochladen",
        "Lâche les photos pour les télécharger",
        "Laat je foto's los om ze te uploaden",
        "Přesuň sem obrázek k nahrání",
        "Rilascia l'immagine per caricarla",
    ],
    writeComment: [
        "Write comment..",
        "Schreibe einen Kommentar..",
        "Écrit un commentaire..",
        "Plaats een opmerking...",
        "Napiš komentář",
        "Scrivi un commento..",
    ],

    // Task
    tasks: [
        "Tasks",
        "Aufgaben",
        "Performances",
        "Opdrachten",
        "Úloha",
        "Obiettivi",
    ],
    all: [
        "All",
        "Alle",
        "Tous",
        "Alle",
        "Vše",
        "Tutti",
    ],
    my: [
        "My",
        "Meine",
        "Mes",
        "Mijn",
        "Moje",
        "Mio",
    ],
    starred: [
        "Starred",
        "Favorisiert",
        "Favorisé",
        "Favorieten",
        "Oblíbené",
        "Preferiti",
    ],
    myTasks: [
        "My tasks",
        "Meine Aufgaben",
        "Mes performances",
        "Mijn opdrachten",
        "Moje úlohy",
        "I miei obbiettivi",
    ],
    declare: [
        "Declare",
        "Deklarieren",
        "Déclarer",
        "Declareren",
        "Deklarovat",
        "Dichiara",
    ],
    undeclare: [
        "Undeclare",
        "Entdeklarieren",
        "Ne plus déclarer",
        "Declaratie verwijderen",
        "Oddeklarovat",
        "Non dichiarato",
    ],
    newTask: [
        "New task",
        "Neue Aufgabe",
        "Nouvelle performance",
        "Nieuwe opdracht",
        "Nová úloha",
        "Nuovi obiettivi",
    ],
    noTaskDeclared: [
        "No declared task.",
        "Keine Aufgabe deklariert.",
        "Pas de performance(s) déclarée(s)",
        "Nog geen gedeclareerde opdracht.",
        "Dosud není deklarována žádná úloha",
        "Ancora nessun obbiettivo dichiarato",
    ],
    noTasks: [
        "No tasks yet, plan a new one!",
        "Keine Aufgaben bis jetzt, plane eine!",
        "Pas de performance jusqu'ici, crées-en une!",
        "Nog geen opdracht, plan een nieuwe!",
        "Dosud žádná úloha, naplánuj!",
        "Nessun obbiettivo, provvedi a selezionarne uno",
    ],
    noTaskInFile: [
        "No valid task in file found",
        "Keine gültige Aufgabe in der Datei gefunden",
        "Aucune tâche valide trouvée dans le fichier",
        "Geen geldige taak in bestand gevonden",
        "V souboru nebyl nalezen žádný platný úkol",
        "Nessuna attività valida nel file trovata"
    ],
    position: [
        "Position",
        "Position",
        "Position",
        "Positie",
        "Poloha",
        "Posizione",
    ],
    startOnLeg: [
        "Start on leg",
        "Start auf Schenkel",
        "Décollage sur branche",
        "Begin op been",
        "Start na rameni",
        "Avvia",
    ],
    taskLockedNotice: [
        "Can't edit task because it was declared.",
        "Aufgabe kann nicht bearbeitet werden weil sie bereits deklariert wurde.",
        "La performance n'est pas accessible car elle a déjà été déclarée.",
        "Opdracht is vergrendeld omdat deze al is gedeclareerd.",
        "Úloha je uzamčena, protože je již deklarována",
        "L'obbiettivo è bloccata perché è già stata dichiarata.",
    ],
    taskplaner: [
        "Taskplaner",
        "Aufgabenplaner",
        "Planifier les performances",
        "Opdrachtplanner",
        "Plánovač úloh",
        "Pianificatore di attività",
    ],
    editTask: [
        "Edit task",
        "Aufgabe bearbeiten",
        "Éditer la performance",
        "Opdracht aanpassen",
        "Upravit úlohu",
        "Modifica obbiettivo",
    ],
    taskName: [
        "Task name",
        "Aufgabenname",
        "Nom de la performance",
        "Naam",
        "Název úlohy",
        "Nome obbiettivo",
    ],
    private: [
        "Only visible for me",
        "Nur sichtbar für mich",
        "Seulement visible pour moi",
        "Privé",
        "Viditelné jen pro mě",
        "Visibile solo a te",
    ],
    turnpoint: [
        "Turnpoint",
        "Wendepunkt",
        "Point de virage",
        "Keerpunt",
        "Otočný body",
        "Punto di svolta",
    ],
    discard: [
        "Discard",
        "Verwerfen",
        "Jeter",
        "Weggooien",
        "Vyřadit",
        "Scartare"
    ],
    cupDragText: [
        "Drag a .cup file here to upload or click to select",
        "Ziehe eine CUP-Datei hierher zum Hochladen oder klicke zum Auswählen",
        "Tire un fichier CUP ici pour le télécharger ou clique pour sélectionner",
        "Sleep een .CUP-bestand hier naar toe om te uploaden of klik om te selecteren",
        "Přetáhni .cup soubor k nahrání, nebo vyber soubor",
        "Trascina un file .cup qui o clicca per selezionarlo",
    ],
    cupDropText: [
        "Drop .cup file to upload",
        "Lasse die CUP-Datei los zum Hochladen",
        "Lâche le fichier CUP pour le télécharger",
        "Sleep een .CUP-bestand om deze te uploaden",
        "Přetáhni .cup soubor k nahrání",
        "Rilascia il file .cup per caricarlo",
    ],
    taskSaved: [
        "Task saved",
        "Aufgabe gespeichert",
        "Performance enregistrée",
        "Opdracht bewaard",
        "Úloha uložena",
        "Obbiettivo salvato",
    ],
    taskDeleted: [
        "Task deleted",
        "Aufgabe gelöscht",
        "Performance supprimée",
        "Opdracht verwijderd",
        "Úloha odstraněna",
        "Obbiettivo cancellato",
    ],
    turnpointHelp: [
        "Click on the map to add a turnpoint.",
        "Klicke auf die Karte für einen Wendepunkt.",
        "Clique sur la carte pour ajouter un point de virage.",
        "Klik op de kaart om een keerpunt toe te voegen.",
        "Klikni na mapu pro přidání otočného bodu",
        "Clicca sulla mappa per aggiungere una meta",
    ],
    editHelp: [
        "Double click or drag to edit.",
        "Doppelt klicken oder ziehen zum Bearbeiten.",
        "Cliquer double ou tirer pour éditer.",
        "Aanpassen kan door verslepen of Dubbelklikken.",
        "Dvojitý klik nebo přetáhni pro úpravu",
        "Fai doppio click o trascina per modificare.",
    ]
}

export function i18n(key: keyof typeof translations): string {
    if (!translations[key]) console.error("Translation not found for", key);
    if (translations[key][i18nStore.current] === "")
        return translations[key][0]; // english
    else
        return translations[key][i18nStore.current];
}
